class BindSignalsMixin:

    def _bind_signal(self):
        self.callback('Bind signal...')
        from PySide6.QtCore import Qt
        from videotrans.mainwin._actions import WinAction
        from videotrans.configure.signal_hub import SignalHub
        from videotrans.configure.config import settings, params
        from videotrans.util.help_misc import open_url, show_glossary_editor

        self.win_action = WinAction(self)
        self.restart_btn.clicked.connect(self.restart_app)
        self.addbackbtn.clicked.connect(self.win_action.get_background)
        self.voice_autorate.toggled.connect(self.win_action.check_voice_autorate)
        self.video_autorate.toggled.connect(self.win_action.check_video_autorate)
        self.enable_cuda.toggled.connect(self.win_action.check_cuda)
        self.tts_type.currentIndexChanged.connect(self.win_action.tts_type_change)

        self.translate_type.currentIndexChanged.connect(self.win_action.set_translate_type)
        self.subtitle_type.currentIndexChanged.connect(self.win_action.set_subtitle_type)
        self.voice_role.currentTextChanged.connect(self.win_action.show_listen_btn)
        self.target_language.currentTextChanged.connect(self.win_action.set_voice_role)

        self.proxy.textChanged.connect(self.win_action.change_proxy)
        self.import_sub.clicked.connect(self.win_action.import_sub_fun)

        self.startbtn.clicked.connect(self.win_action.check_start)
        self.retrybtn.clicked.connect(self.win_action.retry)
        self.btn_save_dir.clicked.connect(self.win_action.get_save_dir)
        self.set_adv_status.clicked.connect(self.win_action.toggle_adv)
        self.btn_get_video.clicked.connect(self.win_action.get_mp4)
        self.listen_btn.clicked.connect(self.win_action.listen_voice_fun)
        self.recogn_type.currentIndexChanged.connect(self.win_action.recogn_type_change)
        self.model_name.currentIndexChanged.connect(self.win_action.model_type_change)

        self.label.clicked.connect(lambda: open_url(url='https://pyvideotrans.com/proxy'))

        self.glossary.clicked.connect(lambda: show_glossary_editor(self))
        self.action_biaozhun.triggered.connect(self.win_action.set_biaozhun)
        self.action_tiquzimu.triggered.connect(self.win_action.set_tiquzimu)

        self.actionbaidu_key.triggered.connect(lambda: self.open_winform('baidu'))
        self.actionali_key.triggered.connect(lambda: self.open_winform('ali'))
        self.set_ass.clicked.connect(lambda: self.open_winform('set_ass'))
        self.actionparakeet_key.triggered.connect(lambda: self.open_winform('parakeet'))
        self.actionsrtmultirole.triggered.connect(lambda: self.open_winform('fn_peiyinrole'))
        self.actionazure_key.triggered.connect(lambda: self.open_winform('azure'))
        self.actionazure_tts.triggered.connect(lambda: self.open_winform('azuretts'))
        self.actiongemini_key.triggered.connect(lambda: self.open_winform('gemini'))
        self.actioncamb_key.triggered.connect(lambda: self.open_winform('cambtts'))
        self.actiontencent_key.triggered.connect(lambda: self.open_winform('tencent'))
        self.actionchatgpt_key.triggered.connect(lambda: self.open_winform('chatgpt'))
        self.actionlibretranslate_key.triggered.connect(lambda: self.open_winform('libre'))
        self.actionai302_key.triggered.connect(lambda: self.open_winform('ai302'))
        self.actionlocalllm_key.triggered.connect(lambda: self.open_winform('localllm'))
        self.actionzijiehuoshan_key.triggered.connect(lambda: self.open_winform('zijiehuoshan'))
        self.actiondeepL_key.triggered.connect(lambda: self.open_winform('deepL'))
        self.actionElevenlabs_key.triggered.connect(lambda: self.open_winform('elevenlabs'))
        self.actiondeepLX_address.triggered.connect(lambda: self.open_winform('deepLX'))
        self.actionclone_address.triggered.connect(lambda: self.open_winform('clone'))
        self.actionkokoro_address.triggered.connect(lambda: self.open_winform('kokoro'))
        self.actionchattts_address.triggered.connect(lambda: self.open_winform('chattts'))
        self.actiontts_api.triggered.connect(lambda: self.open_winform('ttsapi'))
        self.actionminimaxi_api.triggered.connect(lambda: self.open_winform('minimaxi'))
        self.actionrecognapi.triggered.connect(lambda: self.open_winform('recognapi'))
        self.actionsttapi.triggered.connect(lambda: self.open_winform('sttapi'))
        self.actionwhisperx.triggered.connect(lambda: self.open_winform('whisperxapi'))
        self.actiondeepgram.triggered.connect(lambda: self.open_winform('deepgram'))
        self.actionxxl.triggered.connect(lambda: self.open_winform('xxl'))
        self.actioncpp.triggered.connect(lambda: self.open_winform('cpp'))
        self.actionzijierecognmodel_api.triggered.connect(lambda: self.open_winform('zijierecognmodel'))
        self.actiontrans_api.triggered.connect(lambda: self.open_winform('transapi'))
        self.actiontts_gptsovits.triggered.connect(lambda: self.open_winform('gptsovits'))
        self.actiontts_chatterbox.triggered.connect(lambda: self.open_winform('chatterbox'))
        self.actiontts_cosyvoice.triggered.connect(lambda: self.open_winform('cosyvoice'))
        self.actiontts_qwenttslocal.triggered.connect(lambda: self.open_winform('qwenttslocal'))
        self.actionopenaitts_key.triggered.connect(lambda: self.open_winform('openaitts'))
        self.actionxaitts_key.triggered.connect(lambda: self.open_winform('xaitts'))
        self.actionxiaomi_key.triggered.connect(lambda: self.open_winform('xiaomi'))
        self.actionqwentts_key.triggered.connect(lambda: self.open_winform('qwentts'))
        self.actionopenairecognapi_key.triggered.connect(lambda: self.open_winform('openairecognapi'))
        self.actiontts_fishtts.triggered.connect(lambda: self.open_winform('fishtts'))
        self.actiontts_gradiowin.triggered.connect(lambda: self.open_winform('gradiowin'))
        self.actiontts_refaudio.triggered.connect(lambda: self.open_winform('refaudio'))
        self.actiontts_doubao2.triggered.connect(lambda: self.open_winform('doubao2'))
        self.actionzhipuai_key.triggered.connect(lambda: self.open_winform('zhipuai'))
        self.actiondeepseek_key.triggered.connect(lambda: self.open_winform('deepseek'))
        self.actionminimax_key.triggered.connect(lambda: self.open_winform('minimax'))
        self.actionqwenmt_key.triggered.connect(lambda: self.open_winform('qwenmt'))
        self.actionopenrouter_key.triggered.connect(lambda: self.open_winform('openrouter'))
        self.actionsiliconflow_key.triggered.connect(lambda: self.open_winform('siliconflow'))
        self.actionwatermark.triggered.connect(lambda: self.open_winform('fn_watermark'))
        self.actionsepar.triggered.connect(lambda: self.open_winform('fn_separate'))
        self.actionsetini.triggered.connect(lambda: self.open_winform('setini'))
        self.actionvideoandaudio.triggered.connect(lambda: self.open_winform('fn_videoandaudio'))
        self.actionvideoandsrt.triggered.connect(lambda: self.open_winform('fn_videoandsrt'))
        self.actionformatcover.triggered.connect(lambda: self.open_winform('fn_formatcover'))
        self.actionsubtitlescover.triggered.connect(lambda: self.open_winform('fn_subtitlescover'))
        self.action_hebingsrt.triggered.connect(lambda: self.open_winform('fn_hebingsrt'))
        self.action_yinshipinfenli.triggered.connect(lambda: self.open_winform('fn_audiofromvideo'))
        self.action_hun.triggered.connect(lambda: self.open_winform('fn_hunliu'))
        self.action_formatsrtfiles.triggered.connect(lambda: self.open_winform('format_srtfiles_folders'))
        self.action_yingyinhebing.triggered.connect(lambda: self.open_winform('fn_vas'))
        self.action_clipvideo.triggered.connect(lambda: self.open_winform('clipvideo'))
        self.action_textmatching.triggered.connect(lambda: self.open_winform('textmatching'))
        self.action_realtime_stt.triggered.connect(lambda: self.open_winform('realtime_stt'))
        self.action_fanyi.triggered.connect(lambda: self.open_winform('fn_fanyisrt'))
        self.action_yuyinshibie.triggered.connect(lambda: self.open_winform('fn_recogn'))

        self.action_yuyinhecheng.triggered.connect(lambda: self.open_winform('fn_peiyin'))
        self.action_ffmpeg.triggered.connect(lambda: self.win_action.open_url('ffmpeg'))
        self.action_git.triggered.connect(lambda: self.win_action.open_url('git'))
        self.action_discord.triggered.connect(lambda: self.win_action.open_url('hfmirrorcom'))

        self.action_gtrans.triggered.connect(lambda: self.win_action.open_url('gtrans'))
        self.action_cuda.triggered.connect(lambda: self.win_action.open_url('cuda'))
        self.action_online.triggered.connect(self.win_action.lawalert)
        self.action_website.triggered.connect(lambda: self.win_action.open_url('website'))
        self.action_blog.triggered.connect(lambda: self.win_action.open_url('bbs'))
        self.action_issue.triggered.connect(lambda: self.win_action.open_url('issue'))
        self.action_about.triggered.connect(self.win_action.about)
        self.action_clearcache.triggered.connect(self.win_action.clearcache)
        self.action_set_proxy.triggered.connect(self.win_action.proxy_alert)
        self.aisendsrt.toggled.connect(self.checkbox_state_changed)
        self.rightbottom.clicked.connect(self.win_action.about)
        self.statusLabel.clicked.connect(lambda: self.win_action.open_url('help'))

        self.callback('set cursor...')

        self.import_sub.setCursor(Qt.PointingHandCursor)
        self.startbtn.setCursor(Qt.PointingHandCursor)
        self.btn_get_video.setCursor(Qt.PointingHandCursor)
        self.btn_save_dir.setCursor(Qt.PointingHandCursor)
        self.listen_btn.setCursor(Qt.PointingHandCursor)
        self.statusLabel.setCursor(Qt.PointingHandCursor)
        self.rightbottom.setCursor(Qt.PointingHandCursor)
        self.restart_btn.setCursor(Qt.PointingHandCursor)

        SignalHub.instance().new_message.connect(self.win_action.update_data)
        if settings.get('show_more_settings'):
            self.win_action.toggle_adv()

        self.win_action.tts_type_change(self.tts_type.currentIndex())
        _role = params.get('voice_role') or 'No'
        if _role in self.current_rolelist:
            self.voice_role.setCurrentText(_role)

        self.callback('preload TTS win...')
        self.open_winform('fn_peiyin')
        self.callback('preload STT win...')
        self.open_winform('fn_recogn')
        self.callback('preload translate srt win...')
        self.open_winform('fn_fanyisrt')
        self.callback('end')
