from videotrans.component.set_form import BaiduForm, ChatgptForm, DeepLForm, DeepLXForm, TencentForm, ElevenlabsForm, \
    InfoForm, AzureForm, GeminiForm, SetLineRole, YoutubeForm, OttForm, CloneForm, SeparateForm, TtsapiForm, \
    GPTSoVITSForm, TransapiForm, ArticleForm, AzurettsForm,  ChatttsForm, LocalLLMForm, ZijiehuoshanForm, \
    HebingsrtForm, DoubaoForm, FishTTSForm, CosyVoiceForm, AI302Form,  SetINIForm, WatermarkForm, \
    GetaudioForm, HunliuForm, VASForm, Fanyisrt, Recognform, Peiyinform, Videoandaudioform, Videoandsrtform, \
    OpenAITTSForm, RecognAPIForm, OpenaiRecognAPIForm, DownloadModelForm, FormatcoverForm, SubtitlescoverForm, \
    SubtitleEditer,SttAPIForm,VolcEngineTTSForm,F5TTSForm,DeepgramForm,ClaudeForm,LibreForm,AliForm,FreeAIForm,KokoroForm

__all__ = [
    "BaiduForm",
    "ChatgptForm",
    "DeepLForm",
    "DeepLXForm",
    "TencentForm",
    "ElevenlabsForm",
    "InfoForm",
    "AzureForm",
    "GeminiForm",
    "SetLineRole",
    "ElevenlabsForm",
    "YoutubeForm",
    "OttForm",
    "CloneForm",
    "SeparateForm",
    "TtsapiForm",
    "TransapiForm",
    "ArticleForm",
    "AzurettsForm",
    "ChatttsForm",
    "LocalLLMForm",
    "ZijiehuoshanForm",
    "HebingsrtForm",
    "DoubaoForm",
    "FishTTSForm",
    "CosyVoiceForm",
    "AI302Form",
    "SetINIForm",
    "WatermarkForm",
    "GetaudioForm",
    "HunliuForm",
    "VASForm",
    "Fanyisrt",
    "Recognform",
    "Peiyinform",
    "Videoandaudioform",
    "Videoandsrtform",
    "OpenAITTSForm",
    "RecognAPIForm",
    "OpenaiRecognAPIForm",
    "DownloadModelForm",
    "FormatcoverForm",
    "SubtitlescoverForm",
    "SubtitleEditer",
    "SttAPIForm",
    "VolcEngineTTSForm",
    "F5TTSForm",
    "DeepgramForm",
    "ClaudeForm",
    "LibreForm",
    "AliForm",
    "FreeAIForm",
    "KokoroForm"
]
