GOOGLE_INDEX = 0
MICROSOFT_INDEX = 1
M2M100_INDEX = 2

CHATGPT_INDEX = 3
DEEPSEEK_INDEX = 4
GEMINI_INDEX = 5
ZHIPUAI_INDEX = 6
AZUREGPT_INDEX = 7
LOCALLLM_INDEX = 8

OPENROUTER_INDEX = 9
SILICONFLOW_INDEX = 10
AI302_INDEX = 11

QWENMT_INDEX = 12
ZIJIE_INDEX = 13

TENCENT_INDEX = 14
BAIDU_INDEX = 15
DEEPL_INDEX = 16
DEEPLX_INDEX = 17
ALI_INDEX = 18

LIBRE_INDEX = 19
MINIMAX_INDEX = 20
XIAOMI_INDEX = 21
CAMB_INDEX = 22
TRANSAPI_INDEX = 23

AI_TRANS_CHANNELS = [
    CHATGPT_INDEX,
    LOCALLLM_INDEX,
    ZIJIE_INDEX,
    AZUREGPT_INDEX,
    GEMINI_INDEX,
    QWENMT_INDEX,
    AI302_INDEX,
    ZHIPUAI_INDEX,
    SILICONFLOW_INDEX,
    DEEPSEEK_INDEX,
    OPENROUTER_INDEX,
    MINIMAX_INDEX,
    XIAOMI_INDEX,
    CAMB_INDEX
]
