GOOGLE_INDEX = 0
MICROSOFT_INDEX = 1
M2M100_INDEX = 2
HYMT2_INDEX = 3

CHATGPT_INDEX = 4
DEEPSEEK_INDEX = 5
GEMINI_INDEX = 6
ZHIPUAI_INDEX = 7
AZUREGPT_INDEX = 8
LOCALLLM_INDEX = 9

OPENROUTER_INDEX = 10
SILICONFLOW_INDEX = 11
AI302_INDEX = 12

QWENMT_INDEX = 13
ZIJIE_INDEX = 14

TENCENT_INDEX = 15
BAIDU_INDEX = 16
DEEPL_INDEX = 17
DEEPLX_INDEX = 18
ALI_INDEX = 19

LIBRE_INDEX = 20
MINIMAX_INDEX = 21
XIAOMI_INDEX = 22
CAMB_INDEX = 23
TRANSAPI_INDEX = 24

AI_TRANS_CHANNELS = [
    CHATGPT_INDEX,
    LOCALLLM_INDEX,
    ZIJIE_INDEX,
    AZUREGPT_INDEX,
    GEMINI_INDEX,
    QWENMT_INDEX,
    AI302_INDEX,
    ZHIPUAI_INDEX,
    SILICONFLOW_INDEX,
    DEEPSEEK_INDEX,
    OPENROUTER_INDEX,
    MINIMAX_INDEX,
    XIAOMI_INDEX,
    HYMT2_INDEX,
    CAMB_INDEX
]
