#!/usr/bin/env python3
"""
i18n Validation & Type-Checking Tool for pyVideoTrans.

Validates:
1. All translation keys in en.json / zh.json are English (no Chinese/CJK characters in keys).
2. All tr("...") keys used across the codebase exist in all language JSON files.
3. Language JSON files are synchronized (same keys across all supported languages).
4. Format placeholders ({}, {0}, {name}) match between source and translated values.
5. Identifies unused / dead translation keys.
6. Can optionally generate static Python Literal types for IDE / mypy type-checking.
"""

import ast
import argparse
import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Set, Tuple

ROOT_DIR = Path(__file__).resolve().parent.parent
LANG_DIR = ROOT_DIR / "videotrans" / "language"


def extract_code_tr_keys(root: Path) -> Set[str]:
    """Statically extracts all string literal keys passed to tr(...) across the repository."""
    keys: Set[str] = set()
    py_files = list(root.glob("videotrans/**/*.py")) + list(root.glob("*.py"))

    for pf in py_files:
        if pf.name.startswith("scratch_") or pf.name.startswith("test_") or "tools" in pf.parts:
            continue
        try:
            with open(pf, "r", encoding="utf-8") as f:
                tree = ast.parse(f.read(), filename=str(pf))
            for node in ast.walk(tree):
                if isinstance(node, ast.Call):
                    func_name = ""
                    if isinstance(node.func, ast.Name):
                        func_name = node.func.id
                    elif isinstance(node.func, ast.Attribute):
                        func_name = node.func.attr
                    if func_name == "tr" and node.args:
                        arg0 = node.args[0]
                        if isinstance(arg0, ast.Constant) and isinstance(arg0.value, str):
                            keys.add(arg0.value)
                        elif isinstance(arg0, ast.List):
                            for elt in arg0.elts:
                                if isinstance(elt, ast.Constant) and isinstance(elt.value, str):
                                    keys.add(elt.value)
        except Exception as e:
            print(f"[WARN] Error parsing {pf}: {e}", file=sys.stderr)
    return keys


def load_language_files() -> Dict[str, Dict[str, str]]:
    """Loads all JSON files from videotrans/language/."""
    lang_data = {}
    for json_file in LANG_DIR.glob("*.json"):
        with open(json_file, "r", encoding="utf-8") as f:
            lang_data[json_file.stem] = json.load(f)
    return lang_data


def check_cjk_in_keys(lang_data: Dict[str, Dict[str, str]]) -> List[Tuple[str, str]]:
    """Finds keys that contain Chinese/CJK characters."""
    errors = []
    cjk_pattern = re.compile(r"[\u4e00-\u9fff]")
    for lang, data in lang_data.items():
        for key in data.keys():
            if cjk_pattern.search(key):
                errors.append((lang, key))
    return errors


def check_missing_keys(code_keys: Set[str], lang_data: Dict[str, Dict[str, str]]) -> Dict[str, List[str]]:
    """Finds keys used in code tr() that are missing from language JSON files."""
    missing = {}
    for lang, data in lang_data.items():
        missing[lang] = sorted([k for k in code_keys if k not in data])
    return missing


def check_placeholder_mismatches(lang_data: Dict[str, Dict[str, str]]) -> List[Tuple[str, str, int, int]]:
    """Checks for positional format placeholder count mismatches between English and translations."""
    mismatches = []
    en_data = lang_data.get("en", {})
    for lang, data in lang_data.items():
        if lang == "en":
            continue
        for key, trans_val in data.items():
            if not isinstance(trans_val, str):
                continue
            en_val = en_data.get(key, key)
            if not isinstance(en_val, str):
                continue
            en_placeholders = en_val.count("{}")
            val_placeholders = trans_val.count("{}")
            if en_placeholders > 0 and en_placeholders != val_placeholders:
                mismatches.append((lang, key, en_placeholders, val_placeholders))
    return mismatches


def generate_type_file(en_keys: Set[str], output_path: Path):
    """Generates a static Python Literal type definition for TranslationKey."""
    lines = [
        "# Auto-generated by tools/check_i18n.py. Do not edit manually.",
        "from typing import Literal, Union",
        "",
        "TranslationKey = Union[",
    ]
    for k in sorted(en_keys):
        escaped_k = repr(k)
        lines.append(f"    Literal[{escaped_k}],")
    lines.append("    str,  # Fallback for dynamic runtime strings")
    lines.append("]\n")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Generated type definitions at: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Audit and validate i18n translations.")
    parser.add_argument("--strict", action="store_true", help="Exit with code 1 if errors or missing keys are found.")
    parser.add_argument("--report-unused", action="store_true", help="Print list of unused translation keys.")
    parser.add_argument("--generate-types", action="store_true", help="Generate videotrans/configure/_i18n_keys.py.")
    args = parser.parse_args()

    print("🔍 Auditing pyVideoTrans i18n configuration...")

    lang_data = load_language_files()
    if not lang_data:
        print("[ERROR] No language JSON files found in videotrans/language/", file=sys.stderr)
        sys.exit(1)

    code_keys = extract_code_tr_keys(ROOT_DIR)
    print(f"✓ Extracted {len(code_keys)} static tr(...) keys from Python code.")

    has_errors = False

    # Check 1: Non-English Keys
    cjk_keys = check_cjk_in_keys(lang_data)
    if cjk_keys:
        has_errors = True
        print(f"\n❌ Found {len(cjk_keys)} non-English/CJK keys in language files:")
        for lang, k in cjk_keys[:10]:
            print(f"   [{lang}.json] {repr(k)}")
        if len(cjk_keys) > 10:
            print(f"   ... and {len(cjk_keys) - 10} more.")
    else:
        print("✓ All keys in all language JSON files are valid English keys.")

    # Check 2: Missing keys in language files
    missing_by_lang = check_missing_keys(code_keys, lang_data)
    for lang, missing_keys in missing_by_lang.items():
        if missing_keys:
            has_errors = True
            print(f"\n❌ {lang}.json is missing {len(missing_keys)} keys used in code:")
            for k in missing_keys[:10]:
                print(f"   - {repr(k)}")
            if len(missing_keys) > 10:
                print(f"   ... and {len(missing_keys) - 10} more.")
        else:
            print(f"✓ All code tr() keys are present in {lang}.json.")

    # Check 3: Placeholder consistency
    mismatches = check_placeholder_mismatches(lang_data)
    if mismatches:
        print(f"\n⚠️  Found {len(mismatches)} placeholder count mismatches:")
        for lang, key, k_count, v_count in mismatches[:5]:
            print(f"   [{lang}] Key has {k_count} '{{}}' but translation has {v_count}: {repr(key)}")
    else:
        print("✓ Placeholder formatting counts match across translations.")

    # Check 4: Unused keys
    if args.report_unused:
        all_json_keys = set().union(*[set(data.keys()) for data in lang_data.values()])
        unused = sorted(all_json_keys - code_keys)
        print(f"\nℹ️  Found {len(unused)} keys in JSON files not found in static AST code search (some may be dynamic):")
        for k in unused[:15]:
            print(f"   - {repr(k)}")
        if len(unused) > 15:
            print(f"   ... and {len(unused) - 15} more.")

    # Generate types if requested
    if args.generate_types:
        en_keys = set(lang_data.get("en", {}).keys()) | code_keys
        out_path = ROOT_DIR / "videotrans" / "configure" / "_i18n_keys.py"
        generate_type_file(en_keys, out_path)

    if has_errors and args.strict:
        print("\n❌ i18n validation failed with errors.")
        sys.exit(1)
    else:
        print("\n✅ i18n check completed successfully!")


if __name__ == "__main__":
    main()
