# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ott.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtWidgets import QLabel

from videotrans.configure import config


class Ui_chatttsform(object):
    def setupUi(self, chattts):
        chattts.setObjectName("chattts")
        chattts.setWindowModality(QtCore.Qt.NonModal)
        chattts.resize(500, 223)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(chattts.sizePolicy().hasHeightForWidth())
        chattts.setSizePolicy(sizePolicy)
        chattts.setMaximumSize(QtCore.QSize(500, 300))
        self.gridLayout = QtWidgets.QGridLayout(chattts)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(chattts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 35))
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")

        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.chattts_address = QtWidgets.QLineEdit(chattts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chattts_address.sizePolicy().hasHeightForWidth())
        self.chattts_address.setSizePolicy(sizePolicy)
        self.chattts_address.setMinimumSize(QtCore.QSize(400, 35))
        self.chattts_address.setObjectName("chattts_address")
        
        
        
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.chattts_address)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        

        self.set_chattts = QtWidgets.QPushButton(chattts)
        self.set_chattts.setMinimumSize(QtCore.QSize(0, 35))
        self.set_chattts.setObjectName("set_chattts")

        self.test = QtWidgets.QPushButton(chattts)
        self.test.setMinimumSize(QtCore.QSize(0, 30))
        self.test.setObjectName("test")

        label=QLabel('https://github.com/jianchang512/chatTTS-ui')
        self.verticalLayout_2.addWidget(label)

        self.layout_btn = QtWidgets.QHBoxLayout()
        self.layout_btn.setObjectName("layout_btn")

        self.layout_btn.addWidget(self.set_chattts)
        self.layout_btn.addWidget(self.test)

        self.verticalLayout_2.addLayout(self.layout_btn)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(chattts)
        QtCore.QMetaObject.connectSlotsByName(chattts)

    def retranslateUi(self, chattts):
        chattts.setWindowTitle("ChatTTS API")
        self.label.setText("http地址" if config.defaulelang=='zh' else 'ChatTTS URL')
        self.chattts_address.setPlaceholderText('填写 ChatTTS webUI 项目启动后的http地址' if config.defaulelang=='zh' else 'Fill in the HTTP address after the ChatTTS webUI program starts')
        self.set_chattts.setText('保存' if config.defaulelang=='zh' else "Save")
        self.test.setText('测试' if config.defaulelang=='zh' else "Test")
