# run again.  Do not edit this file unless you know what you are doing.
from PySide6 import QtWidgets
from PySide6.QtCore import QMetaObject, QSize, Qt
from PySide6.QtWidgets import QLabel, QLineEdit, QPushButton, QSizePolicy, QHBoxLayout, QVBoxLayout

from videotrans.configure.config import tr
from videotrans.util.help_misc import show_refaudio_win


class Ui_chatterboxform(object):
    def setupUi(self, chatterboxform):
        self.has_done = False
        if not chatterboxform.objectName():
            chatterboxform.setObjectName("chatterboxform")
        chatterboxform.setWindowModality(Qt.NonModal)
        chatterboxform.resize(600, 250)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(chatterboxform.sizePolicy().hasHeightForWidth())
        chatterboxform.setSizePolicy(sizePolicy)
        chatterboxform.setMaximumSize(QSize(600, 250))

        self.wrap_h = QHBoxLayout(chatterboxform)
        self.wrap_h.setObjectName(u"wrap_h")
        self.inner_v = QVBoxLayout()

        cfg_h = QHBoxLayout()
        cfg_label = QLabel()
        cfg_label.setObjectName("cfg_label")
        cfg_label.setText('cfg_weight(0-1)')
        cfg_label.setMinimumSize(QSize(0, 35))
        self.cfg_weight = QLineEdit()
        self.cfg_weight.setObjectName("cfg_weight")
        self.cfg_weight.setMinimumSize(QSize(0, 35))
        cfg_h.addWidget(cfg_label)
        cfg_h.addWidget(self.cfg_weight)
        self.inner_v.addLayout(cfg_h)

        exaggeration_h = QHBoxLayout()
        exaggeration_label = QLabel()
        exaggeration_label.setObjectName("exaggeration_label")
        exaggeration_label.setText('exaggeration(0.25-2.0)')
        exaggeration_label.setMinimumSize(QSize(0, 35))
        self.exaggeration = QLineEdit()
        self.exaggeration.setObjectName("exaggeration")
        self.exaggeration.setMinimumSize(QSize(0, 35))
        exaggeration_h.addWidget(exaggeration_label)
        exaggeration_h.addWidget(self.exaggeration)
        self.inner_v.addLayout(exaggeration_h)


        h4 = QHBoxLayout()

        self.save = QPushButton()
        self.save.setObjectName("save")
        self.save.setMinimumSize(QSize(0, 35))

        self.test = QPushButton()
        self.test.setObjectName("test")
        self.test.setMinimumSize(QSize(0, 35))
        h4.addWidget(self.save)
        h4.addWidget(self.test)

        ref_btn = QtWidgets.QPushButton()
        ref_btn.setText(tr("Set reference audio"))
        ref_btn.clicked.connect(show_refaudio_win)
        h4.addWidget(ref_btn)

        self.inner_v.addLayout(h4)
        # end
        self.wrap_h.addLayout(self.inner_v)

        self.retranslateUi(chatterboxform)
        QMetaObject.connectSlotsByName(chatterboxform)

    # setupUi

    def retranslateUi(self, chatterboxform):
        chatterboxform.setWindowTitle("Chatterbox-TTS")
        self.save.setText(tr("Save"))
        self.test.setText(tr("Test"))
