# run again.  Do not edit this file unless you know what you are doing.
from PySide6 import QtWidgets, QtCore
from PySide6.QtCore import QMetaObject, QSize, Qt
from PySide6.QtWidgets import QLabel, QLineEdit, QPlainTextEdit, QPushButton, QSizePolicy

from videotrans.configure.config import tr
from videotrans.util import tools


class Ui_cosyvoiceform(object):
    def setupUi(self, cosyvoiceform):
        self.has_done = False
        if not cosyvoiceform.objectName():
            cosyvoiceform.setObjectName("cosyvoiceform")
        cosyvoiceform.setWindowModality(Qt.NonModal)
        cosyvoiceform.resize(600, 500)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(cosyvoiceform.sizePolicy().hasHeightForWidth())
        cosyvoiceform.setSizePolicy(sizePolicy)
        cosyvoiceform.setMaximumSize(QSize(600, 500))

        # 创建一个垂直布局
        v1 = QtWidgets.QVBoxLayout(cosyvoiceform)
        v1.addWidget(QLabel('使用该接口需启动 CosyVoice2 官方项目的webui.py'))
        h1 = QtWidgets.QHBoxLayout()
        self.label = QLabel()
        self.label.setObjectName("label")
        self.label.setMinimumSize(QSize(0, 35))
        self.api_url = QLineEdit(cosyvoiceform)
        self.api_url.setObjectName("api_url")
        self.api_url.setMinimumSize(QSize(0, 35))
        h1.addWidget(self.label)
        h1.addWidget(self.api_url)
        v1.addLayout(h1)

        self.label_4 = QLabel(cosyvoiceform)
        self.label_4.setObjectName("label_4")
        self.label_4.setText('参考音频#音频文字内容【参考音频时长不得大于10s，否则出错】')
        v1.addWidget(self.label_4)

        self.role = QPlainTextEdit(cosyvoiceform)
        self.role.setObjectName("role")
        self.role.setMinimumHeight(100)
        self.role.setReadOnly(False)
        v1.addWidget(self.role)


        h2 = QtWidgets.QHBoxLayout()
        self.save = QPushButton(cosyvoiceform)
        self.save.setObjectName("save")
        self.save.setMinimumSize(QSize(0, 35))

        self.test = QPushButton(cosyvoiceform)
        self.test.setObjectName("test")
        self.test.setMinimumSize(QSize(0, 35))

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: tools.open_url(url='https://pyvideotrans.com/cosyvoice'))

        h2.addWidget(self.save)
        h2.addWidget(self.test)
        h2.addWidget(help_btn)

        v1.addLayout(h2)

        self.retranslateUi(cosyvoiceform)

        QMetaObject.connectSlotsByName(cosyvoiceform)

    # setupUi

    def retranslateUi(self, cosyvoiceform):
        tips = """
# 需要预先部署CosyVoice2官方项目,然后启动 webui.py
# CosyVoice项目地址 https://github.com/FunAudioLLM/CosyVoice

参考音频填写：
每行都由#符号分割为两部分，第一部分是wav音频路径，第二部分是该音频对应的文字内容，可填写多行。
wav音频最佳时长3-10s，音频必须存放在本软件目录下的 f5-tts 文件夹内，然后在此填写文件名称

参考音频填写示例：
1.wav#你好啊亲爱的朋友
2.wav#你好啊朋友们


"""

        cosyvoiceform.setWindowTitle("CosyVoice2 API")

        self.role.setPlaceholderText(tips)

        self.save.setText(tr("Save"))
        self.api_url.setPlaceholderText("填写CosyVoice的webui.py启动后的地址，默认  http://127.0.0.1:8000")
        self.label.setText("CosyVoice API")
        self.test.setText(tr("Test"))
