# run again.  Do not edit this file unless you know what you are doing.

from PySide6 import QtCore, QtWidgets
from PySide6.QtCore import Qt
from PySide6.QtGui import QIcon
from PySide6.QtWidgets import QDialog

from videotrans.configure.config import tr, ROOT_DIR
from videotrans.util.help_misc import open_url


class Ui_deeplx(QDialog):
    def __init__(self):
        super().__init__()
        self.setWindowIcon(QIcon(f"{ROOT_DIR}/videotrans/styles/icon.ico"))
        self.setupUi(self)
    def setupUi(self, form):
        self.has_done = False
        form.setObjectName("form")
        form.resize(500, 300)

        self.verticalLayout = QtWidgets.QVBoxLayout(form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")

        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName("formLayout_3")

        self.label = QtWidgets.QLabel()
        self.label.setMinimumSize(QtCore.QSize(100, 35))
        self.label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.deeplx_address = QtWidgets.QLineEdit()
        self.deeplx_address.setMinimumSize(QtCore.QSize(320, 35))
        self.deeplx_address.setObjectName("deeplx_address")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.deeplx_address)

        self.label2 = QtWidgets.QLabel()
        self.label2.setMinimumSize(QtCore.QSize(100, 35))
        self.label2.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.label2.setObjectName("label2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label2)
        self.deeplx_key = QtWidgets.QLineEdit()
        self.deeplx_key.setMinimumSize(QtCore.QSize(320, 35))
        self.deeplx_key.setObjectName("deeplx_key")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.deeplx_key)

        self.verticalLayout.addLayout(self.formLayout_2)
        self.verticalLayout.addLayout(self.formLayout_3)

        self.set_deeplx = QtWidgets.QPushButton()
        self.set_deeplx.setMinimumSize(QtCore.QSize(0, 35))
        self.set_deeplx.setObjectName("set_deeplx")

        self.test = QtWidgets.QPushButton()
        self.test.setObjectName("test")

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: open_url(url='https://pyvideotrans.com/deeplx'))

        h1 = QtWidgets.QHBoxLayout()
        h1.addWidget(self.set_deeplx)
        h1.addWidget(self.test)
        h1.addWidget(help_btn)

        self.verticalLayout.addLayout(h1)

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        form.setWindowTitle("DeepLx")
        self.label.setText(tr("API URL"))
        self.label2.setText(tr("SK"))
        self.deeplx_key.setPlaceholderText(
            tr("Input your deeplx key"))
        self.deeplx_address.setPlaceholderText(
            tr("Input your deeplx api url"))
        self.set_deeplx.setText(tr("Save"))
        self.test.setText(tr("Test"))
