# run again.  Do not edit this file unless you know what you are doing.
from PySide6 import QtWidgets, QtCore
from PySide6.QtCore import QMetaObject, QRect, QSize, Qt
from PySide6.QtWidgets import QLabel, QLineEdit, QPlainTextEdit, QPushButton, QSizePolicy

from videotrans.configure.config import tr
from videotrans.util.help_misc import show_refaudio_win, open_url


class Ui_gradiowinform(object):
    def setupUi(self, gradiowinform):
        self.has_done = False
        if not gradiowinform.objectName():
            gradiowinform.setObjectName("gradiowinform")
        gradiowinform.setWindowModality(Qt.NonModal)
        gradiowinform.resize(600, 500)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(gradiowinform.sizePolicy().hasHeightForWidth())
        gradiowinform.setSizePolicy(sizePolicy)
        gradiowinform.setMaximumSize(QSize(600, 500))

        v1 = QtWidgets.QVBoxLayout(gradiowinform)

        h1indextts_url = QtWidgets.QHBoxLayout()
        self.indextts_urllabel = QLabel('Index-TTS URL')
        self.indextts_urllabel.setObjectName("indextts_urllabel")
        self.indextts_urllabel.setMinimumSize(QSize(0, 35))
        self.indextts_url = QLineEdit()
        self.indextts_url.setObjectName("indextts_url")
        self.indextts_url.setMinimumSize(QSize(0, 35))        
        self.indextts_url.setPlaceholderText('URL ')      
        h1indextts_url.addWidget(self.indextts_urllabel)
        h1indextts_url.addWidget(self.indextts_url)
        self.indextts_urltest = QPushButton(tr("Test"))        
        self.index_tts_version = QtWidgets.QComboBox()
        self.index_tts_version.addItems([' V1 ',' V2 '])
        self.index_tts_version.setToolTip(tr("When using Index-TTS, select v1 or v2."))

        h1indextts_url.addWidget(self.index_tts_version)
        h1indextts_url.addWidget(self.indextts_urltest)

        v1.addLayout(h1indextts_url)

        h1sparktts_url = QtWidgets.QHBoxLayout()
        self.sparktts_urllabel = QLabel('Spark-TTS URL')
        self.sparktts_urllabel.setObjectName("sparktts_urllabel")
        self.sparktts_urllabel.setMinimumSize(QSize(0, 35))
        self.sparktts_url = QLineEdit()
        self.sparktts_url.setObjectName("sparktts_url")
        self.sparktts_url.setPlaceholderText('URL ')
        self.sparktts_url.setMinimumSize(QSize(0, 35))        
        h1sparktts_url.addWidget(self.sparktts_urllabel)
        h1sparktts_url.addWidget(self.sparktts_url)
        self.sparktts_urltest = QPushButton(tr("Test"))        
        h1sparktts_url.addWidget(self.sparktts_urltest)
        v1.addLayout(h1sparktts_url)


        

        h1voxcpmtts_url = QtWidgets.QHBoxLayout()
        self.voxcpmtts_urllabel = QLabel('VoxCPM URL')
        self.voxcpmtts_urllabel.setObjectName("voxcpmtts_urllabel")
        self.voxcpmtts_urllabel.setMinimumSize(QSize(0, 35))
        self.voxcpmtts_url = QLineEdit()
        self.voxcpmtts_url.setPlaceholderText('URL ')
        self.voxcpmtts_url.setObjectName("voxcpmtts_url")
        self.voxcpmtts_url.setMinimumSize(QSize(0, 35))        
        self.voxcpmtts_version = QtWidgets.QComboBox()
        # hf 是  voxcpm 官方在huggingface.co 上的示例中所需参数，和官方代码库中v2版的demo参数不一致
        self.voxcpmtts_version.addItems(['v2','v1','hf'])

        h1voxcpmtts_url.addWidget(self.voxcpmtts_urllabel)
        h1voxcpmtts_url.addWidget(self.voxcpmtts_url)
        h1voxcpmtts_url.addWidget(self.voxcpmtts_version)       
        
        
        self.voxcpmtts_urltest = QPushButton(tr("Test"))        
        h1voxcpmtts_url.addWidget(self.voxcpmtts_urltest)
        v1.addLayout(h1voxcpmtts_url) 

        h2 = QtWidgets.QHBoxLayout()

        self.save = QPushButton()
        self.save.setObjectName("save")
        self.save.setGeometry(QRect(10, 450, 93, 35))
        self.save.setMinimumSize(QSize(0, 35))
       

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: open_url(url='https://pyvideotrans.com/gradiowin'))


        h2.addWidget(self.save)
        ref_btn = QtWidgets.QPushButton()
        ref_btn.setText(tr("Set reference audio"))
        ref_btn.clicked.connect(show_refaudio_win)
        h2.addWidget(ref_btn)
        h2.addWidget(help_btn)
        v1.addLayout(h2)

        self.retranslateUi(gradiowinform)

        QMetaObject.connectSlotsByName(gradiowinform)


    def retranslateUi(self, gradiowinform):

        gradiowinform.setWindowTitle("Index/VoxCPM/Spark" +tr('This channel needs deployed and started before available'))
        self.save.setText(tr("Save"))
