# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets
from PySide6.QtCore import Qt
from PySide6.QtGui import QIcon
from PySide6.QtWidgets import QDialog

from videotrans.configure.config import tr, settings, params, ROOT_DIR
from videotrans.util.help_misc import open_url


class Ui_infistar(QDialog):
    def __init__(self):
        super().__init__()
        self.setWindowIcon(QIcon(f"{ROOT_DIR}/videotrans/styles/icon.ico"))
        self.setupUi(self)
    def setupUi(self, infistarform):
        self.has_done = False
        infistarform.setObjectName("infistarform")
        infistarform.setWindowModality(QtCore.Qt.NonModal)
        infistarform.resize(600, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(infistarform.sizePolicy().hasHeightForWidth())
        infistarform.setSizePolicy(sizePolicy)
        infistarform.setMaximumSize(QtCore.QSize(600, 600))

        v1 = QtWidgets.QVBoxLayout(infistarform)

        h3 = QtWidgets.QHBoxLayout()
        h4 = QtWidgets.QHBoxLayout()

        self.label_0 = QtWidgets.QPushButton()
        self.label_0.setGeometry(QtCore.QRect(10, 10, 580, 35))
        self.label_0.setStyleSheet("background-color: rgba(255, 255, 255,0);text-align:left")
        self.label_0.setCursor(Qt.PointingHandCursor)
        self.label_0.setText('Infistar.cc - ' + tr('OpenAI-compatible gateway, one Key for GPT, Claude, Gemini, DeepSeek, Qwen'))
        self.label_0.clicked.connect(lambda: open_url(url='https://infistar.cc/register?aff=9H6H7RR9&ref_source=link'))
        v1.addWidget(self.label_0)

        self.label_3 = QtWidgets.QLabel(infistarform)
        self.label_3.setObjectName("label_3")
        self.infistar_key = QtWidgets.QLineEdit(infistarform)
        self.infistar_key.setMinimumSize(QtCore.QSize(0, 35))
        self.infistar_key.setObjectName("infistar_key")
        h3.addWidget(self.label_3)
        h3.addWidget(self.infistar_key)
        v1.addLayout(h3)

        h_token = QtWidgets.QHBoxLayout()

        label_token = QtWidgets.QLabel()
        label_token.setObjectName("label_token")
        label_token.setText(tr("Maximum output token"))
        self.max_token = QtWidgets.QLineEdit()
        self.max_token.setMinimumSize(QtCore.QSize(0, 35))
        self.max_token.setObjectName("max_token")

        h_token.addWidget(label_token)
        h_token.addWidget(self.max_token)
        v1.addLayout(h_token)

        h_model = QtWidgets.QHBoxLayout()
        self.label_selectmodel = QtWidgets.QLabel()
        self.label_selectmodel.setObjectName("label_selectmodel")
        self.label_selectmodel.setText(tr("Model"))
        self.infistar_model = QtWidgets.QComboBox()
        self.infistar_model.setMinimumSize(QtCore.QSize(0, 35))
        self.infistar_model.setObjectName("infistar_model")
        h_model.addWidget(self.label_selectmodel)
        h_model.addWidget(self.infistar_model)
        v1.addLayout(h_model)

        self.label_allmodels = QtWidgets.QLabel()
        self.label_allmodels.setObjectName("label_allmodels")
        self.label_allmodels.setText(
            tr("Fill in all available models, separated by commas. After filling in, you can select them above"))
        v1.addWidget(self.label_allmodels)

        self.edit_allmodels = QtWidgets.QPlainTextEdit()
        self.edit_allmodels.setObjectName("edit_allmodels")
        v1.addWidget(self.edit_allmodels)

        self.label_4 = QtWidgets.QLabel(infistarform)
        self.label_4.setObjectName("label_4")

        self.template = QtWidgets.QPlainTextEdit(infistarform)
        self.template.setObjectName("template")
        self.template.setReadOnly(True)
        v1.addWidget(self.label_4)
        v1.addWidget(self.template)

        self.set = QtWidgets.QPushButton(infistarform)
        self.set.setMinimumSize(QtCore.QSize(0, 35))
        self.set.setObjectName("set")

        self.test = QtWidgets.QPushButton()
        self.test.setMinimumSize(QtCore.QSize(0, 30))
        self.test.setObjectName("test")
        self.test.setText(tr("Test"))

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Get API Key"))
        help_btn.clicked.connect(lambda: open_url(url='https://infistar.cc/register?aff=9H6H7RR9&ref_source=link'))

        h4.addWidget(self.set)
        h4.addWidget(self.test)
        h4.addWidget(help_btn)
        v1.addLayout(h4)
        self.template.setPlainText(tr("Prompt: Please open the {} file directly to modify it", 'infistar', 'infistar'))

        self.retranslateUi(infistarform)
        QtCore.QMetaObject.connectSlotsByName(infistarform)

    def update_ui(self):
        allmodels_str = settings.get('infistar_model', '')
        allmodels = str(settings.get('infistar_model', '')).split(',')
        self.infistar_model.clear()
        self.infistar_model.addItems(allmodels)
        self.edit_allmodels.setPlainText(allmodels_str)
        self.infistar_key.setText(str(params.get("infistar_key", '')))
        self.infistar_model.setCurrentText(params.get("infistar_model", ''))
        self.max_token.setText(str(params.get("infistar_max_token", '')))

    def retranslateUi(self, infistarform):
        infistarform.setWindowTitle("Infistar")
        self.label_3.setText(tr("SK"))
        self.label_4.setText(tr("{lang} represents the target language name, do not delete it."))
        self.set.setText(tr('Save'))
