# run again.  Do not edit this file unless you know what you are doing.

from PySide6 import QtCore, QtWidgets
from PySide6.QtCore import Qt
from PySide6.QtGui import QIcon
from PySide6.QtWidgets import QDialog

from videotrans.configure.config import tr, ROOT_DIR
from videotrans.util.help_misc import open_url


class Ui_libre(QDialog):
    def __init__(self):
        super().__init__()
        self.setWindowIcon(QIcon(f"{ROOT_DIR}/videotrans/styles/icon.ico"))
        self.setupUi(self)
    def setupUi(self, form):
        self.has_done = False
        form.setObjectName("form")
        form.resize(500, 300)

        self.verticalLayout = QtWidgets.QVBoxLayout(form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")

        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName("formLayout_3")

        self.label = QtWidgets.QLabel()
        self.label.setMinimumSize(QtCore.QSize(100, 35))
        self.label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.address = QtWidgets.QLineEdit()
        self.address.setMinimumSize(QtCore.QSize(320, 35))
        self.address.setObjectName("address")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.address)

        self.label2 = QtWidgets.QLabel()
        self.label2.setMinimumSize(QtCore.QSize(100, 35))
        self.label2.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.label2.setObjectName("label2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label2)
        self.key = QtWidgets.QLineEdit()
        self.key.setMinimumSize(QtCore.QSize(320, 35))
        self.key.setObjectName("key")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.key)

        self.verticalLayout.addLayout(self.formLayout_2)
        self.verticalLayout.addLayout(self.formLayout_3)

        self.set = QtWidgets.QPushButton()
        self.set.setMinimumSize(QtCore.QSize(0, 35))
        self.set.setObjectName("set")

        self.test = QtWidgets.QPushButton()
        self.test.setObjectName("test")

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: open_url(url='https://pyvideotrans.com/libretranslate'))

        h1 = QtWidgets.QHBoxLayout()
        h1.addWidget(self.set)
        h1.addWidget(self.test)
        h1.addWidget(help_btn)

        self.verticalLayout.addLayout(h1)

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        form.setWindowTitle("LibreTranslate"+tr('This channel needs deployed and started before available'))
        self.label.setText(tr("API URL"))
        self.label2.setText(tr('SK'))
        self.key.setPlaceholderText(tr("Input your libretranslate key"))
        self.address.setPlaceholderText(tr('API URL'))
        self.set.setText(tr("Save"))
        self.test.setText(tr("Test"))
