# run again.  Do not edit this file unless you know what you are doing.
from PySide6 import QtWidgets, QtCore
from PySide6.QtCore import QMetaObject, QSize, Qt
from PySide6.QtWidgets import QLabel, QLineEdit,  QPushButton, QSizePolicy

from videotrans.configure.config import tr,app_cfg,params,settings,logger
from videotrans.util import tools


class Ui_minimaxiform(object):
    def setupUi(self, minimaxiform):
        self.has_done = False
        if not minimaxiform.objectName():
            minimaxiform.setObjectName("minimaxiform")
        minimaxiform.setWindowModality(Qt.NonModal)
        minimaxiform.resize(800, 300)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(minimaxiform.sizePolicy().hasHeightForWidth())
        minimaxiform.setSizePolicy(sizePolicy)
        minimaxiform.setMaximumSize(QSize(800, 300))

        v1 = QtWidgets.QVBoxLayout(minimaxiform)



        h1 = QtWidgets.QHBoxLayout()
        label_api = QLabel()
        label_api.setObjectName("label_api")
        label_api.setText(tr('API minimax'))
        self.apiurl = QtWidgets.QComboBox()
        self.apiurl.setObjectName("apiurl")
        self.apiurl.addItems(["api.minimaxi.com", "api.minimax.io"])
        h1.addWidget(label_api)
        h1.addWidget(self.apiurl)
        v1.addLayout(h1)
        
        h3 = QtWidgets.QHBoxLayout()
        hmodel = QtWidgets.QHBoxLayout()
        h5 = QtWidgets.QHBoxLayout()

        self.label_3 = QLabel()
        self.label_3.setObjectName("label_3")
        self.apikey = QLineEdit()
        self.apikey.setObjectName("apikey")
        h3.addWidget(self.label_3)
        h3.addWidget(self.apikey)



        label_5 = QLabel()
        label_5.setText(tr("Emotion"))
        self.emotion = QtWidgets.QComboBox()
        self.emotion.addItems(["happy", "sad", "angry", "fearful", "disgusted", "surprised", "neutral"])


        label_6 = QLabel()
        label_6.setText(tr("Model"))
        self.model = QtWidgets.QComboBox()
        self.model.addItems([
            "speech-2.8-turbo",
            "speech-2.8-hd",
            "speech-2.6-hd",
            "speech-2.6-turbo",
            "speech-02-hd",
            "speech-02-turbo"
        ])

        hmodel.addWidget(label_6)
        hmodel.addWidget(self.model)

        h5.addWidget(label_5)
        h5.addWidget(self.emotion)

        v1.addLayout(h3)
        v1.addLayout(hmodel)
        v1.addLayout(h5)


        h4 = QtWidgets.QHBoxLayout()
        self.save = QPushButton()
        self.save.setObjectName("save")
        self.save.setMinimumSize(QSize(0, 35))
        self.test = QPushButton()
        self.test.setObjectName("test")
        self.test.setMinimumSize(QSize(0, 35))

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: tools.open_url(url='https://pyvideotrans.com/minimaxi'))

        h4.addWidget(self.save)
        h4.addWidget(self.test)
        h4.addWidget(help_btn)
        v1.addLayout(h4)

        self.retranslateUi(minimaxiform)

        QMetaObject.connectSlotsByName(minimaxiform)

    # setupUi

    def retranslateUi(self, minimaxiform):
        minimaxiform.setWindowTitle("Minimaxi API")
        self.label_3.setText(tr("SK"))
        self.save.setText(tr("Save"))
        self.apikey.setPlaceholderText(
            tr("SK"))
        self.test.setText(tr("Test"))

