# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets
from PySide6.QtCore import Qt

from videotrans.configure.config import tr,app_cfg,params,settings,logger
from videotrans.util import tools


class Ui_mittsform(object):
    def setupUi(self, mittsform):
        self.has_done = False
        mittsform.setObjectName("mittsform")
        mittsform.setWindowModality(QtCore.Qt.NonModal)
        mittsform.resize(600, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mittsform.sizePolicy().hasHeightForWidth())
        mittsform.setSizePolicy(sizePolicy)
        mittsform.setMaximumSize(QtCore.QSize(600, 300))

        v1 = QtWidgets.QVBoxLayout(mittsform)



        h2 = QtWidgets.QHBoxLayout()
        self.label_2 = QtWidgets.QLabel(mittsform)
        self.label_2.setMinimumSize(QtCore.QSize(0, 35))
        self.label_2.setSizeIncrement(QtCore.QSize(0, 35))
        self.label_2.setObjectName("label_2")
        self.mitts_key = QtWidgets.QLineEdit(mittsform)
        self.mitts_key.setMinimumSize(QtCore.QSize(0, 35))
        self.mitts_key.setObjectName("mitts_key")
        h2.addWidget(self.label_2)
        h2.addWidget(self.mitts_key)
        v1.addLayout(h2)


        h4 = QtWidgets.QHBoxLayout()

        self.set_mitts = QtWidgets.QPushButton(mittsform)
        self.set_mitts.setMinimumSize(QtCore.QSize(0, 35))
        self.set_mitts.setObjectName("set_mitts")

        self.test_mitts = QtWidgets.QPushButton(mittsform)
        self.test_mitts.setMinimumSize(QtCore.QSize(0, 30))
        self.test_mitts.setObjectName("test_mitts")

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: tools.open_url(url='https://pyvideotrans.com/mitts'))

        h4.addWidget(self.set_mitts)
        h4.addWidget(self.test_mitts)
        h4.addWidget(help_btn)
        v1.addLayout(h4)

        self.retranslateUi(mittsform)
        QtCore.QMetaObject.connectSlotsByName(mittsform)

    def update_ui(self):

        if params.get("mitts_key",''):
            self.mitts_key.setText(params.get("mitts_key",''))

    def retranslateUi(self, mittsform):
        mittsform.setWindowTitle("xiaomi TTS")
        self.set_mitts.setText(tr("Save"))
        self.test_mitts.setText(tr("Test"))
        self.mitts_key.setPlaceholderText("SK")
        self.label_2.setText(tr("SK"))
