# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets
from PySide6.QtCore import Qt

from videotrans.configure.config import tr,app_cfg,params,settings,logger,ROOT_DIR
from videotrans.util import tools


class Ui_mossttsform(object):
    def setupUi(self, clone):
        self.has_done = False
        clone.setObjectName("clone")
        clone.setWindowModality(QtCore.Qt.NonModal)
        clone.resize(500, 223)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(clone.sizePolicy().hasHeightForWidth())
        clone.setSizePolicy(sizePolicy)


        self.verticalLayout = QtWidgets.QVBoxLayout(clone)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(clone)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 35))
        self.label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")

        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.clone_address = QtWidgets.QLineEdit(clone)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clone_address.sizePolicy().hasHeightForWidth())
        self.clone_address.setSizePolicy(sizePolicy)
        self.clone_address.setMinimumSize(QtCore.QSize(200, 35))
        self.clone_address.setObjectName("clone_address")

        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.clone_address)
        self.verticalLayout.addLayout(self.formLayout_2)
        
        
        # add start
        local_role_tip = QtWidgets.QLabel(tr("Reference Audio#Audio Text"))
        local_role_tip.setStyleSheet('color:#999')
        local_role_tip.setWordWrap(True)
        self.local_role = QtWidgets.QPlainTextEdit()
        self.local_role.setPlaceholderText(tr("Reference audio needs to be in wav format, with a duration of no more than 12 seconds, and stored in the /f5-tts directory of this software"))
        self.local_role.setMinimumHeight(120)

        preset_text_label = QtWidgets.QLabel('预制角色试听文案')
        self.preset_test_text_input = QtWidgets.QLineEdit()
        self.preset_test_text_input.setPlaceholderText('留空则使用预制角色默认文案')
        self.preset_test_text_input.setMinimumHeight(35)

        self.verticalLayout.addWidget(local_role_tip)
        self.verticalLayout.addWidget(self.local_role)
        self.verticalLayout.addWidget(preset_text_label)
        self.verticalLayout.addWidget(self.preset_test_text_input)



        local_test_wrap = QtWidgets.QHBoxLayout()
        local_test_label = QtWidgets.QLabel(tr('Local role'))
        self.local_role_combo = QtWidgets.QComboBox()
        self.local_role_combo.setMinimumHeight(35)
        self.local_test_btn = QtWidgets.QPushButton(tr('Test local role'))
        self.local_test_btn.setMinimumHeight(35)
        local_test_wrap.addWidget(local_test_label)
        local_test_wrap.addWidget(self.local_role_combo)
        local_test_wrap.addWidget(self.local_test_btn)
        self.verticalLayout.insertLayout(6, local_test_wrap)

        # add end

        self.set_clone = QtWidgets.QPushButton(clone)
        self.set_clone.setMinimumSize(QtCore.QSize(0, 35))
        self.set_clone.setObjectName("set_clone")

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: tools.open_url(url='https://pyvideotrans.com/mosstts'))

        self.layout_btn = QtWidgets.QHBoxLayout()
        self.layout_btn.setObjectName("layout_btn")

        self.layout_btn.addWidget(self.set_clone)
        self.layout_btn.addWidget(help_btn)

        self.verticalLayout.addLayout(self.layout_btn)

        self.retranslateUi(clone)
        QtCore.QMetaObject.connectSlotsByName(clone)

    def retranslateUi(self, clone):
        clone.setWindowTitle("MossTTS")
        self.label.setText('API URL')
        self.clone_address.setPlaceholderText('')
        self.set_clone.setText(tr("Save"))
