# run again.  Do not edit this file unless you know what you are doing.
from PySide6 import QtWidgets, QtCore
from PySide6.QtCore import QMetaObject, QSize, Qt
from PySide6.QtWidgets import QLabel, QLineEdit, QPushButton, QSizePolicy

from videotrans.configure.config import tr
from videotrans.util.help_misc import show_refaudio_win, open_url


class Ui_omnivoiceform(object):
    def setupUi(self, omnivoiceform):
        self.has_done = False
        if not omnivoiceform.objectName():
            omnivoiceform.setObjectName("omnivoiceform")
        omnivoiceform.setWindowModality(Qt.NonModal)
        omnivoiceform.resize(600, 250)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(omnivoiceform.sizePolicy().hasHeightForWidth())
        omnivoiceform.setSizePolicy(sizePolicy)
        omnivoiceform.setMaximumSize(QSize(600, 250))

        # 创建一个垂直布局
        v1 = QtWidgets.QVBoxLayout(omnivoiceform)
        h1 = QtWidgets.QHBoxLayout()
        self.label = QLabel()
        self.label.setObjectName("label")
        self.label.setMinimumSize(QSize(0, 35))
        self.api_url = QLineEdit()
        self.api_url.setObjectName("api_url")
        self.api_url.setMinimumSize(QSize(0, 35))
        h1.addWidget(self.label)
        h1.addWidget(self.api_url)
        v1.addLayout(h1)


        


        h2 = QtWidgets.QHBoxLayout()
        self.save = QPushButton()
        self.save.setObjectName("save")
        self.save.setMinimumSize(QSize(0, 35))

        self.test = QPushButton()
        self.test.setObjectName("test")
        self.test.setMinimumSize(QSize(0, 35))

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))

        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: open_url(url='https://pyvideotrans.com/omnivoice'))

        h2.addWidget(self.save)
        h2.addWidget(self.test)

        ref_btn = QtWidgets.QPushButton()
        ref_btn.setText(tr("Set reference audio"))
        ref_btn.clicked.connect(show_refaudio_win)
        h2.addWidget(ref_btn)
        h2.addWidget(help_btn)

        v1.addLayout(h2)

        self.retranslateUi(omnivoiceform)

        QMetaObject.connectSlotsByName(omnivoiceform)

    # setupUi

    def retranslateUi(self, omnivoiceform):
        omnivoiceform.setWindowTitle("Omnivoice"+tr('This channel needs deployed and started before available'))

        self.save.setText(tr("Save"))
        self.api_url.setPlaceholderText("URL http://127.0.0.1:8081")
        self.label.setText("URL")
        self.test.setText(tr("Test"))
