# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ott.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtWidgets import QLabel
from videotrans.configure import config

class Ui_ottform(object):
    def setupUi(self, ottform):
        ottform.setObjectName("ottform")
        ottform.setWindowModality(QtCore.Qt.NonModal)
        ottform.resize(400, 223)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ottform.sizePolicy().hasHeightForWidth())
        ottform.setSizePolicy(sizePolicy)
        ottform.setMaximumSize(QtCore.QSize(400, 300))
        self.gridLayout = QtWidgets.QGridLayout(ottform)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(ottform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 35))
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.ott_address = QtWidgets.QLineEdit(ottform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ott_address.sizePolicy().hasHeightForWidth())
        self.ott_address.setSizePolicy(sizePolicy)
        self.ott_address.setMinimumSize(QtCore.QSize(210, 35))
        self.ott_address.setObjectName("ott_address")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ott_address)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.set_ott = QtWidgets.QPushButton(ottform)
        self.set_ott.setMinimumSize(QtCore.QSize(0, 35))
        self.set_ott.setObjectName("set_ott")
        
        label=QLabel(config.transobj['The ott project at'])
        self.verticalLayout_2.addWidget(label)
        
        self.verticalLayout_2.addWidget(self.set_ott)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(ottform)
        QtCore.QMetaObject.connectSlotsByName(ottform)

    def retranslateUi(self, ottform):
        ottform.setWindowTitle("OTT离线翻译" if config.defaulelang=='zh' else 'Offline Text Translate')
        self.label.setText("OTT_api")
        self.ott_address.setPlaceholderText('在此填写你的OTT项目部署后的http地址' if config.defaulelang=='zh' else 'Fill in the HTTP address for your OTT project deployment here')
        self.set_ott.setText('保存' if config.defaulelang=='zh' else "Save")
