# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets
from PySide6.QtCore import Qt
from PySide6.QtWidgets import (QWidget, QVBoxLayout, QHBoxLayout,
                               QPushButton, QComboBox, QLabel, QScrollArea)

from videotrans import tts
from videotrans.configure import config
from videotrans.configure.config import box_lang


class Ui_peiyinrole(object):
    def setupUi(self, peiyinrole):
        self.has_done = False
        if not peiyinrole.objectName():
            peiyinrole.setObjectName(u"peiyinrole")
        peiyinrole.resize(850, 650)

        # 全局变量初始化
        self.srt_path = None
        self.subtitles = []
        self.error_msg = ""
        if not hasattr(config, 'dubbing_role'):
            config.dubbing_role = {}

        self.main_layout = QtWidgets.QVBoxLayout(peiyinrole)
        self.main_layout.setObjectName("main_layout")

        # 1. 顶部文件导入区域
        self.import_layout = QtWidgets.QHBoxLayout()
        self.hecheng_importbtn = QPushButton("导入SRT文件..." if config.defaulelang == 'zh' else 'Import SRT file...')
        self.hecheng_importbtn.setMinimumHeight(40)
        self.hecheng_importbtn.setCursor(Qt.PointingHandCursor)
        self.clear_button = QtWidgets.QPushButton("清空" if config.defaulelang == 'zh' else 'Clear')
        self.clear_button.setMinimumHeight(40)
        self.clear_button.setFixedWidth(100)
        self.clear_button.setCursor(Qt.PointingHandCursor)

        self.import_layout.addWidget(self.hecheng_importbtn)
        self.import_layout.addWidget(self.clear_button)
        self.main_layout.addLayout(self.import_layout)

        # 2. 字幕显示和分配区域
        # 2.1 字幕滚动区域
        self.subtitle_scroll_area = QScrollArea()
        self.subtitle_scroll_area.setWidgetResizable(True)
        self.subtitle_scroll_area.setMinimumHeight(200)
        self.scroll_area_widget_contents = QWidget()
        self.subtitle_layout = QVBoxLayout(self.scroll_area_widget_contents)  # 字幕行将被添加到这里
        self.subtitle_layout.setAlignment(Qt.AlignTop)
        self.subtitle_scroll_area.setWidget(self.scroll_area_widget_contents)
        self.main_layout.addWidget(self.subtitle_scroll_area)

        # 2.2 角色分配工具栏
        self.assign_role_layout = QHBoxLayout()
        self.assign_role_label = QLabel("为选中行分配角色:" if config.defaulelang == 'zh' else "Assign role to selected:")
        self.tmp_rolelist = QComboBox()  # 这个就是新的角色选择框
        self.tmp_rolelist.setMinimumWidth(200)
        self.assign_role_button = QPushButton("确认分配" if config.defaulelang == 'zh' else "Assign")
        self.assign_role_button.setCursor(Qt.PointingHandCursor)
        self.assign_role_layout.addWidget(self.assign_role_label)
        self.assign_role_layout.addWidget(self.tmp_rolelist)
        self.assign_role_layout.addWidget(self.assign_role_button)
        self.assign_role_layout.addStretch()
        self.main_layout.addLayout(self.assign_role_layout)

        # 3. TTS 设置区域 (基本保持不变)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_10 = QtWidgets.QLabel()
        self.label_10.setMinimumSize(QtCore.QSize(0, 30))
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.hecheng_language = QtWidgets.QComboBox()
        self.hecheng_language.setMinimumSize(QtCore.QSize(0, 30))
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hecheng_language)

        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setFormAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_8 = QtWidgets.QLabel()
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.tts_type = QtWidgets.QComboBox()
        self.tts_type.setMinimumSize(QtCore.QSize(0, 30))
        self.tts_type.addItems(tts.TTS_NAME_LIST)
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tts_type)
        self.horizontalLayout_10.addLayout(self.formLayout_7)
        self.horizontalLayout_10.addLayout(self.formLayout_3)

        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_11 = QtWidgets.QLabel()
        self.label_11.setMinimumSize(QtCore.QSize(0, 30))
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.hecheng_role = QtWidgets.QComboBox()  # 这个是原始的，现在作为角色源
        self.hecheng_role.setMinimumSize(QtCore.QSize(0, 30))
        self.hecheng_role.addItems(['No'])
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hecheng_role)
        self.horizontalLayout_10.addLayout(self.formLayout_4)

        self.listen_btn = QtWidgets.QPushButton()
        self.listen_btn.setFixedWidth(80)
        self.listen_btn.setText(config.uilanglist.get("Trial dubbing"))
        self.horizontalLayout_10.addWidget(self.listen_btn)
        self.main_layout.addLayout(self.horizontalLayout_10)

        # 4. 速率、音量等设置
        self.horizontalLayout_10_1 = QtWidgets.QHBoxLayout()
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.label_12 = QtWidgets.QLabel()
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.hecheng_rate = QtWidgets.QSpinBox()
        self.hecheng_rate.setMinimum(-100)
        self.hecheng_rate.setMaximum(100)
        self.hecheng_rate.setMinimumWidth(90)
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hecheng_rate)
        self.horizontalLayout_10_1.addLayout(self.formLayout_5)
        self.voice_autorate = QtWidgets.QCheckBox()
        self.horizontalLayout_10_1.addWidget(self.voice_autorate)

        self.edge_volume_layout = QtWidgets.QHBoxLayout()
        self.volume_label = QtWidgets.QLabel("音量+" if config.defaulelang == 'zh' else "Volume+")
        self.volume_rate = QtWidgets.QSpinBox()
        self.volume_rate.setMinimum(-95)
        self.volume_rate.setMaximum(100)
        self.volume_rate.setMinimumWidth(90)
        self.pitch_label = QtWidgets.QLabel("音调+" if config.defaulelang == 'zh' else "Pitch+")
        self.pitch_rate = QtWidgets.QSpinBox()
        self.pitch_rate.setMinimum(-100)
        self.pitch_rate.setMaximum(100)
        self.pitch_rate.setMinimumWidth(90)
        self.out_format_label = QtWidgets.QLabel('输出格式' if config.defaulelang == 'zh' else 'Out format')
        self.out_format = QtWidgets.QComboBox()
        self.out_format.addItems(['wav', "mp3", "m4a"])
        self.save_to_srt = QtWidgets.QCheckBox()
        self.edge_volume_layout.addWidget(self.volume_label)
        self.edge_volume_layout.addWidget(self.volume_rate)
        self.edge_volume_layout.addWidget(self.pitch_label)
        self.edge_volume_layout.addWidget(self.pitch_rate)
        self.edge_volume_layout.addWidget(self.out_format_label)
        self.edge_volume_layout.addWidget(self.out_format)
        self.edge_volume_layout.addWidget(self.save_to_srt)
        self.horizontalLayout_10_1.addLayout(self.edge_volume_layout)
        self.main_layout.addLayout(self.horizontalLayout_10_1)

        # 5. 开始/停止按钮和日志
        self.bottom_layout = QtWidgets.QVBoxLayout()
        h1 = QtWidgets.QHBoxLayout()
        self.hecheng_startbtn = QtWidgets.QPushButton()
        self.hecheng_startbtn.setMinimumSize(QtCore.QSize(200, 40))
        self.hecheng_startbtn.setCursor(Qt.PointingHandCursor)
        self.hecheng_stop = QtWidgets.QPushButton('停止' if config.defaulelang == 'zh' else 'Stop')
        self.hecheng_stop.setFixedWidth(100)
        self.hecheng_stop.setDisabled(True)
        self.hecheng_stop.setCursor(Qt.PointingHandCursor)
        h1.addWidget(self.hecheng_startbtn)
        h1.addWidget(self.hecheng_stop)
        self.bottom_layout.addLayout(h1)

        self.loglabel = QtWidgets.QPushButton()
        self.loglabel.setStyleSheet('''color:#148cd2;background-color:transparent''')
        self.bottom_layout.addWidget(self.loglabel)

        self.hecheng_opendir = QtWidgets.QPushButton()
        self.hecheng_opendir.setStyleSheet("""background-color:transparent""")
        self.hecheng_opendir.setMinimumSize(QtCore.QSize(100, 35))
        self.hecheng_opendir.setCursor(Qt.PointingHandCursor)
        self.bottom_layout.addWidget(self.hecheng_opendir)
        self.main_layout.addLayout(self.bottom_layout)

        self.retranslateUi(peiyinrole)
        QtCore.QMetaObject.connectSlotsByName(peiyinrole)

    def retranslateUi(self, peiyinrole):
        peiyinrole.setWindowTitle(
            '字幕多角色配音：为每条字幕分配一个声音' if config.defaulelang == 'zh' else 'Subtitle multi-role dubbing: assign a voice to each subtitle')
        self.label_10.setText(box_lang.get("Subtitle lang"))
        self.label_8.setText("TTS" if config.defaulelang != 'zh' else '配音渠道')
        self.label_11.setText("默认角色" if config.defaulelang == 'zh' else "Default Role")
        self.label_12.setText(box_lang.get("Speed change"))
        self.hecheng_rate.setToolTip(box_lang.get("Negative deceleration, positive acceleration"))
        self.voice_autorate.setText(box_lang.get("Automatic acceleration?"))
        self.save_to_srt.setText("Save to original location" if config.defaulelang != 'zh' else '保存到原位置')
        self.save_to_srt.setToolTip(
            "If checked, the synthesized audio is saved to the original folder where the srt file is located." if config.defaulelang != 'zh' else '如果选中，则合成后音频保存到srt文件所在原文件夹内')
        self.hecheng_startbtn.setText(box_lang.get("Start"))
        self.hecheng_opendir.setText(box_lang.get("Open dir"))
