# run again.  Do not edit this file unless you know what you are doing.
from PySide6 import QtWidgets, QtCore
from PySide6.QtCore import QMetaObject, QSize, Qt
from PySide6.QtWidgets import QLabel, QLineEdit, QPlainTextEdit, QPushButton, QSizePolicy

from videotrans.configure.config import tr
from videotrans.configure import config
from videotrans.util import tools


class Ui_qwenttslocal(object):
    def setupUi(self, qwenttslocal):
        self.has_done = False
        if not qwenttslocal.objectName():
            qwenttslocal.setObjectName("qwenttslocal")
        qwenttslocal.setWindowModality(Qt.NonModal)
        qwenttslocal.resize(1000, 500)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(qwenttslocal.sizePolicy().hasHeightForWidth())
        qwenttslocal.setSizePolicy(sizePolicy)
        qwenttslocal.setMaximumSize(QSize(1000, 500))

        # 创建一个垂直布局
        v1 = QtWidgets.QVBoxLayout(qwenttslocal)
        tipslabel=QLabel('Qwen3-TTS(本地)，需部署Qwen3-TTS项目并启动后可用，项目开源地址\n https://github.com/QwenLM/Qwen3-TTS\n如果你不会部署，也可使用整合包: https://pyvideotrans.com/qwen-tts' if config.defaulelang=='zh' else 'Qwen3-TTS(Local), first deploy \nhttps://github.com/QwenLM/Qwen3-TTS\n https://pyvideotrans.com/qwen-tts')
        tipslabel.setWordWrap(True)
        v1.addWidget(tipslabel)
        h1 = QtWidgets.QHBoxLayout()
        self.label = QLabel()
        self.label.setObjectName("label")
        self.label.setMinimumSize(QSize(0, 35))
        self.api_url = QLineEdit()
        self.api_url.setObjectName("api_url")
        self.api_url.setMinimumSize(QSize(0, 35))
        h1.addWidget(self.label)
        h1.addWidget(self.api_url)
        v1.addLayout(h1)


        h1_prompt = QtWidgets.QHBoxLayout()
        self.instruct_text = QLineEdit()
        h1_prompt.addWidget(QLabel('自定义音色提示词' if config.defaulelang=='zh' else 'Custom Voice Prompt'))
        h1_prompt.addWidget(self.instruct_text)
        v1.addLayout(h1_prompt)
        
        self.label_4 = QLabel()
        self.label_4.setObjectName("label_4")
        self.label_4.setText(tr('Reference Audio#Audio Text'))
        v1.addWidget(self.label_4)
        


        self.role = QPlainTextEdit()
        self.role.setObjectName("role")
        self.role.setMinimumHeight(100)
        self.role.setReadOnly(False)
        v1.addWidget(self.role)


        h2 = QtWidgets.QHBoxLayout()
        self.save = QPushButton()
        self.save.setObjectName("save")
        self.save.setMinimumSize(QSize(0, 35))

        self.test = QPushButton()
        self.test.setObjectName("test")
        self.test.setMinimumSize(QSize(0, 35))

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: tools.open_url(url='https://pyvideotrans.com/qwen-tts'))

        h2.addWidget(self.save)
        h2.addWidget(self.test)
        h2.addWidget(help_btn)

        v1.addLayout(h2)

        self.retranslateUi(qwenttslocal)

        QMetaObject.connectSlotsByName(qwenttslocal)

    # setupUi

    def retranslateUi(self, qwenttslocal):
        tips = """
这是Qwen3-TTS的本地版本，必须先部署 Qwen3-TTS 官方项目,并启动 qwen-tts-demo Qwen/模型 后才可使用
Qwen3-TTS 项目地址 https://github.com/QwenLM/Qwen3-TTS
若不会部署，也可使用整合包 https://pyvideotrans.com/qwen-tts

命令1：qwen-tts-demo Qwen/Qwen3-TTS-12Hz-1.7B-Base
命令2：qwen-tts-demo Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice

命令1所用模型可用于视频翻译中的音色克隆，即 clone 音色，也可使用在此处填写的参考音频
命令2所用模型可用于使用模型内置的音色，例如 Vivian、Sohee等，并可以使用 prompt 对音色进行指导

参考音频填写：
每行都由#符号分割为两部分，第一部分是wav音频名称，第二部分是该音频对应的文字内容。
wav音频最佳时长3-10s，音频必须存放在本软件目录下的 f5-tts 文件夹内，然后在此填写文件名称

参考音频填写示例：
1.wav#你好啊亲爱的朋友
2.wav#你好啊朋友们


# prompt 填写提示词，在使用模型内置的音色时，可作为发音指导词，例如请使用愤怒的声音

""" if config.defaulelang=='zh' else """
This is the local version of Qwen3-TTS, which requires deploying the official Qwen3-TTS project and launching the qwen-tts-demo Qwen/model before it can be used
Qwen3-TTS Project Address: https://github.com/QwenLM/Qwen3-TTS
If you are not familiar with deployment, you can also use the integrated package at https://pyvideotrans.com/qwen-tts

Command 1: qwen-tts-demo Qwen/Qwen3-TTS-12Hz-1.7B-Base
Command 2: qwen-tts-demo Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice

The model used in Command 1 can be employed for voice cloning in video translation, i.e., clone voice, and also utilizes the reference audio provided here
The model used in Command 2 supports built-in vocal styles such as Vivian and Sohee, and allows prompt-based guidance for vocal style customization

Reference audio filling:
Each line is divided into two parts by the # symbol, with the first part being the WAV audio file name and the second part being the corresponding text content.
The optimal duration for WAV audio is 3-10 seconds. The audio must be stored in the f5-tts folder under this software's directory, and then the file name should be entered here

Example for filling in based on audio reference:
Hello, dear friend
2.wav#Hello, friends


# prompt Fill in the prompt word, which can serve as pronunciation guidance when using the model's built-in voice tones, such as "Please use an angry tone."


"""

        qwenttslocal.setWindowTitle(f"Qwen3-TTS {tr('Local')}")

        self.role.setPlaceholderText(tips)

        self.save.setText(tr("Save"))
        self.api_url.setPlaceholderText("webui url http://127.0.0.1:8000")
        self.label.setText("WebUI URL")
        self.test.setText(tr("Test"))
