# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets
from PySide6.QtCore import Qt

from videotrans.configure import config
from videotrans.util import tools


class Ui_qwenttsform(object):
    def setupUi(self, qwenttsform):
        self.has_done = False
        qwenttsform.setObjectName("qwenttsform")
        qwenttsform.setWindowModality(QtCore.Qt.NonModal)
        qwenttsform.resize(600, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(qwenttsform.sizePolicy().hasHeightForWidth())
        qwenttsform.setSizePolicy(sizePolicy)
        qwenttsform.setMaximumSize(QtCore.QSize(600, 600))

        v1 = QtWidgets.QVBoxLayout(qwenttsform)

        h2 = QtWidgets.QHBoxLayout()
        self.label_2 = QtWidgets.QLabel(qwenttsform)
        self.label_2.setMinimumSize(QtCore.QSize(0, 35))
        self.label_2.setSizeIncrement(QtCore.QSize(0, 35))
        self.label_2.setObjectName("label_2")
        self.qwentts_key = QtWidgets.QLineEdit(qwenttsform)
        self.qwentts_key.setMinimumSize(QtCore.QSize(0, 35))
        self.qwentts_key.setObjectName("qwentts_key")
        h2.addWidget(self.label_2)
        h2.addWidget(self.qwentts_key)
        v1.addLayout(h2)

        h3 = QtWidgets.QHBoxLayout()
        self.label_3 = QtWidgets.QLabel(qwenttsform)
        self.label_3.setObjectName("label_3")
        self.qwentts_model = QtWidgets.QComboBox(qwenttsform)
        self.qwentts_model.setMinimumSize(QtCore.QSize(0, 35))
        self.qwentts_model.setObjectName("qwentts_model")
        h3.addWidget(self.label_3)
        h3.addWidget(self.qwentts_model)

        v1.addLayout(h3)

        v1.addWidget(
            QtWidgets.QLabel('角色列表(Dylan:北京男/Jada:吴语女/Sunny:四川女)' if config.defaulelang == 'zh' else 'Role list'))
        self.edit_roles = QtWidgets.QPlainTextEdit(qwenttsform)
        self.edit_roles.setMinimumHeight(40)
        self.edit_roles.setObjectName("edit_roles")
        v1.addWidget(self.edit_roles)

        h4 = QtWidgets.QHBoxLayout()

        self.set_qwentts = QtWidgets.QPushButton(qwenttsform)
        self.set_qwentts.setMinimumSize(QtCore.QSize(0, 35))
        self.set_qwentts.setObjectName("set_qwentts")

        self.test_qwentts = QtWidgets.QPushButton(qwenttsform)
        self.test_qwentts.setMinimumSize(QtCore.QSize(0, 30))
        self.test_qwentts.setObjectName("test_qwentts")

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText("查看填写教程" if config.defaulelang == 'zh' else "Fill out the tutorial")
        help_btn.clicked.connect(lambda: tools.open_url(url='https://pyvideotrans.com/qwentts'))

        h4.addWidget(self.set_qwentts)
        h4.addWidget(self.test_qwentts)
        h4.addWidget(help_btn)
        v1.addLayout(h4)

        self.retranslateUi(qwenttsform)
        QtCore.QMetaObject.connectSlotsByName(qwenttsform)

    def retranslateUi(self, qwenttsform):
        qwenttsform.setWindowTitle("Qwen TTS")
        self.label_3.setText('选择模型' if config.defaulelang == 'zh' else "Model")
        self.set_qwentts.setText('保存' if config.defaulelang == 'zh' else "Save")
        self.test_qwentts.setText('测试..' if config.defaulelang == 'zh' else "Test..")
        self.qwentts_key.setPlaceholderText("QwenTTS API KEY")
        self.label_2.setText("API KEY")
