# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets
from PySide6.QtCore import Qt

from videotrans.configure import config
from videotrans.configure.config import tr
from videotrans.util import tools


class Ui_qwenmtform(object):
    def setupUi(self, qwenmtform):
        self.has_done = False
        qwenmtform.setObjectName("qwenmtform")
        qwenmtform.setWindowModality(QtCore.Qt.NonModal)
        qwenmtform.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(qwenmtform.sizePolicy().hasHeightForWidth())
        qwenmtform.setSizePolicy(sizePolicy)
        qwenmtform.setMaximumSize(QtCore.QSize(800, 600))

        v1 = QtWidgets.QVBoxLayout(qwenmtform)




        self.label_0 = QtWidgets.QPushButton()
        self.label_0.setGeometry(QtCore.QRect(10, 10, 580, 35))
        self.label_0.setStyleSheet("background-color: rgba(255, 255, 255,0);text-align:left")
        self.label_0.setText(tr('Configure Alibaba Bailian Qwen-MT model or other text models or Qwen3-ASR speech recognition model here'))
        v1.addWidget(self.label_0)

        self.label_2 = QtWidgets.QLabel(qwenmtform)
        self.label_2.setMinimumSize(QtCore.QSize(0, 35))
        self.label_2.setSizeIncrement(QtCore.QSize(0, 35))
        self.label_2.setObjectName("label_2")
        self.qwenmt_key = QtWidgets.QLineEdit(qwenmtform)
        self.qwenmt_key.setMinimumSize(QtCore.QSize(0, 35))
        self.qwenmt_key.setObjectName("qwenmt_key")
        h2 = QtWidgets.QHBoxLayout()
        h2.addWidget(self.label_2)
        h2.addWidget(self.qwenmt_key)



        v1.addLayout(h2)

        label_domains = QtWidgets.QLabel(qwenmtform)
        label_domains.setMinimumSize(QtCore.QSize(0, 35))
        label_domains.setSizeIncrement(QtCore.QSize(0, 35))
        label_domains.setObjectName("label_domains")
        label_domains.setText(tr("Translation style prompt"))
        self.qwenmt_domains = QtWidgets.QLineEdit(qwenmtform)
        self.qwenmt_domains.setMinimumSize(QtCore.QSize(0, 35))
        self.qwenmt_domains.setObjectName("qwenmt_domains")
        self.qwenmt_domains.setPlaceholderText(tr("Fill in a natural language text (must be English) describing your domain, which will be provided to the model as a prompt"))
        h3 = QtWidgets.QHBoxLayout()
        h3.addWidget(label_domains)
        h3.addWidget(self.qwenmt_domains)
        v1.addLayout(h3)



        h_model = QtWidgets.QHBoxLayout()
        self.label_selectmodel = QtWidgets.QLabel()
        self.label_selectmodel.setObjectName("label_selectmodel")
        self.label_selectmodel.setText(tr("Subtitle translation model (must start with qwen-mt or other qwen text generation model)"))
        self.qwenmt_model = QtWidgets.QComboBox()
        self.qwenmt_model.setMinimumSize(QtCore.QSize(0, 35))
        self.qwenmt_model.setObjectName("qwenmt_model")
        h_model.addWidget(self.label_selectmodel)
        h_model.addWidget(self.qwenmt_model)
        v1.addLayout(h_model)

        h_asr_model = QtWidgets.QHBoxLayout()
        label_asr_selectmodel = QtWidgets.QLabel()
        label_asr_selectmodel.setObjectName("label_asr_selectmodel")
        label_asr_selectmodel.setText(tr("Speech recognition model (must start with qwen3-asr)"))
        self.qwenmt_asr_model = QtWidgets.QComboBox()
        self.qwenmt_asr_model.setMinimumSize(QtCore.QSize(0, 35))
        self.qwenmt_asr_model.setObjectName("qwenmt_asr_model")
        h_asr_model.addWidget(label_asr_selectmodel)
        h_asr_model.addWidget(self.qwenmt_asr_model)
        v1.addLayout(h_asr_model)

        self.label_allmodels = QtWidgets.QLabel()
        self.label_allmodels.setObjectName("label_allmodels")
        self.label_allmodels.setText(
            tr("Fill in all available models, separated by commas. After filling in, you can select them above"))
        v1.addWidget(self.label_allmodels)

        self.edit_allmodels = QtWidgets.QPlainTextEdit()
        self.edit_allmodels.setObjectName("edit_allmodels")
        v1.addWidget(self.edit_allmodels)

        self.template = QtWidgets.QPlainTextEdit()
        self.template.setObjectName("template")
        self.template.setReadOnly(True)
        self.template.setPlainText(tr("Prompt: Please open the {} file directly to modify it",
                                            'bailian' if config.defaulelang == 'zh' else 'bailian-en'))

        v1.addWidget(self.template)

        self.set = QtWidgets.QPushButton(qwenmtform)
        self.set.setMinimumSize(QtCore.QSize(0, 35))
        self.set.setObjectName("set")

        self.test = QtWidgets.QPushButton()
        self.test.setMinimumSize(QtCore.QSize(0, 30))
        self.test.setObjectName("test")
        self.test.setText(tr("Test"))

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: tools.open_url(url='https://pyvideotrans.com/qwen-mt'))

        h4 = QtWidgets.QHBoxLayout()
        h4.addWidget(self.set)
        h4.addWidget(self.test)
        h4.addWidget(help_btn)
        v1.addLayout(h4)

        self.retranslateUi(qwenmtform)
        QtCore.QMetaObject.connectSlotsByName(qwenmtform)

    def update_ui(self):
        from videotrans.configure import config
        config.settings = config.parse_init()
        allmodels_str = config.settings.get('qwenmt_model','')
        allmodels = str(config.settings.get('qwenmt_model','')).split(',')
        self.qwenmt_model.clear()
        self.qwenmt_asr_model.clear()
        self.qwenmt_model.addItems([ it  for it in allmodels if not it.startswith('qwen3-asr')])
        self.qwenmt_asr_model.addItems([ it  for it in allmodels if it.startswith('qwen3-asr')])
        self.edit_allmodels.setPlainText(allmodels_str)

        self.qwenmt_key.setText(config.params.get("qwenmt_key",''))
        self.qwenmt_domains.setText(config.params.get("qwenmt_domains",''))
        self.qwenmt_model.setCurrentText(config.params.get("qwenmt_model",''))
        self.qwenmt_asr_model.setCurrentText(config.params.get("qwenmt_asr_model",''))

    def retranslateUi(self, qwenmtform):
        qwenmtform.setWindowTitle(tr("Ali-BaiLian API/Qwen3-ASR AI"))
        self.label_2.setText(f"{tr('Ali-Bailian')} {tr('SK')}")
        self.set.setText(tr("Save"))
