# run again.  Do not edit this file unless you know what you are doing.
from PySide6 import QtWidgets, QtCore
from PySide6.QtCore import QMetaObject, QSize, Qt
from PySide6.QtWidgets import QLabel, QLineEdit, QPlainTextEdit, QPushButton, QSizePolicy

from videotrans.configure.config import tr
from videotrans.configure import config
from videotrans.util import tools


class Ui_qwenttslocal(object):
    def setupUi(self, qwenttslocal):
        self.has_done = False
        if not qwenttslocal.objectName():
            qwenttslocal.setObjectName("qwenttslocal")
        qwenttslocal.setWindowModality(Qt.NonModal)
        qwenttslocal.resize(1000, 500)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(qwenttslocal.sizePolicy().hasHeightForWidth())
        qwenttslocal.setSizePolicy(sizePolicy)
        qwenttslocal.setMaximumSize(QSize(1000, 500))

        # 创建一个垂直布局
        v1 = QtWidgets.QVBoxLayout(qwenttslocal)
        tipslabel=QLabel('Qwen3-TTS(本地)，需部署Qwen3-TTS项目并启动后可用，项目开源地址\n https://github.com/QwenLM/Qwen3-TTS\n如果你不会部署，也可使用整合包: https://pyvideotrans.com/qwen-tts' if config.defaulelang=='zh' else 'Qwen3-TTS (local) requires deployment and startup of the Qwen3-TTS project to be available. The project open-source address is:\nhttps://github.com/QwenLM/Qwen3-TTS\nIf you are unsure how to deploy it, you can also use the integration package: \nhttps://pyvideotrans.com/qwen-tts')
        tipslabel.setWordWrap(True)
        v1.addWidget(tipslabel)
        h1 = QtWidgets.QHBoxLayout()
        self.label = QLabel()
        self.label.setObjectName("label")
        self.label.setMinimumSize(QSize(0, 35))
        self.api_url = QLineEdit()
        self.api_url.setObjectName("api_url")
        self.api_url.setMinimumSize(QSize(0, 35))
        h1.addWidget(self.label)
        h1.addWidget(self.api_url)
        v1.addLayout(h1)


        h1_prompt = QtWidgets.QHBoxLayout()
        self.instruct_text = QLineEdit()
        h1_prompt.addWidget(QLabel('自定义音色提示词' if config.defaulelang=='zh' else 'Custom Voice Prompt'))
        h1_prompt.addWidget(self.instruct_text)
        v1.addLayout(h1_prompt)
        
        self.label_4 = QLabel()
        self.label_4.setObjectName("label_4")
        self.label_4.setText(tr('Reference Audio#Audio Text'))
        v1.addWidget(self.label_4)
        


        self.role = QPlainTextEdit()
        self.role.setObjectName("role")
        self.role.setMinimumHeight(100)
        self.role.setReadOnly(False)
        v1.addWidget(self.role)


        h2 = QtWidgets.QHBoxLayout()
        self.save = QPushButton()
        self.save.setObjectName("save")
        self.save.setMinimumSize(QSize(0, 35))

        self.test = QPushButton()
        self.test.setObjectName("test")
        self.test.setMinimumSize(QSize(0, 35))

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: tools.open_url(url='https://pyvideotrans.com/qwen-tts'))

        h2.addWidget(self.save)
        h2.addWidget(self.test)
        h2.addWidget(help_btn)

        v1.addLayout(h2)

        self.retranslateUi(qwenttslocal)

        QMetaObject.connectSlotsByName(qwenttslocal)

    # setupUi

    def retranslateUi(self, qwenttslocal):
        tips = """
如果想在视频翻译中使用 clone 角色复制原视频音色，或者使用你的参考音频，则必须启动 Qwen3-TTS-12Hz-1.7B-Base 语音克隆模型
如果想使用qwen-tts模型的内置音色，例如 Vivian、Sohee等(可以填写prompt对音色微调),则必须启动 Qwen3-TTS-12Hz-1.7B-CustomVoice 自定义音色模型

参考音频填写：
每行都由#符号分割为两部分，第一部分是wav音频名称，第二部分是该音频对应的文字内容。
wav音频最佳时长3-10s，音频必须存放在本软件目录下的 f5-tts 文件夹内，然后在此填写文件名称

参考音频填写示例：
1.wav#你好啊亲爱的朋友
2.wav#你好啊朋友们

【在本页面点击测试时，如果未填写参考音频，将连接Qwen3-TTS-12Hz-1.7B-Base语音克隆模型，如果有填写，则连接Qwen3-TTS-12Hz-1.7B-CustomVoice自定义音色模型，请根据你的需要进行处理】

# prompt 填写提示词，在使用模型内置的音色时(Vivian、Sohee等)，可作为发音指导词，例如请使用愤怒的声音

""" if config.defaulelang=='zh' else """
If you want to use the clone role to copy the original video audio in video translation, or use your reference audio, you must start the `Qwen3-TTS-12Hz-1.7B-Base` model.

If you want to use the built-in audio of the `qwen-tts` model, such as Vivian, Sohee, etc. (you can fill in the prompt to fine-tune the audio), you must start the `Qwen3-TTS-12Hz-1.7B-CustomVoice` model.

Reference Audio Input: Each line is separated into two parts by the `#` symbol. The first part is the name of the WAV audio file, and the second part is the corresponding text content.

The optimal length for a WAV audio file is 3-10 seconds. The audio file must be located in the `f5-tts` folder within this software's directory. Enter the file name here.

Sample audio entries:
1. wav#Hello, dear friend
2. wav#Hello, friends

# prompt Enter a prompt word. When using the model's built-in voices (Vivian, Sohee, etc.), this can serve as pronunciation guidance. For example, please use an angry voice.

"""

        qwenttslocal.setWindowTitle(f"Qwen3-TTS {tr('Local')}")

        self.role.setPlaceholderText(tips)

        self.save.setText(tr("Save"))
        self.api_url.setPlaceholderText("webui url http://127.0.0.1:8000")
        self.label.setText("WebUI URL")
        self.test.setText(tr("Test"))
