# run again.  Do not edit this file unless you know what you are doing.
from PySide6 import QtWidgets
from PySide6.QtCore import QMetaObject, QSize, Qt
from PySide6.QtWidgets import QLabel, QPlainTextEdit, QPushButton, QSizePolicy

from videotrans.configure.config import tr, params,ROOT_DIR
from videotrans.util.help_misc import show_error, set_process
from pathlib import Path

class Ui_refform(object):
    def setupUi(self, refform):
        refform.setWindowModality(Qt.NonModal)
        refform.resize(600, 500)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(refform.sizePolicy().hasHeightForWidth())
        refform.setSizePolicy(sizePolicy)
        refform.setMaximumSize(QSize(600, 500))

        v1 = QtWidgets.QVBoxLayout(refform)

        label = QLabel()
        label.setObjectName("label")
        label.setText(tr("Reference Audio#Audio Text"))
        v1.addWidget(label)
        req = QLabel()
        req.setText(tr("Reference audio needs to be in wav format"))
        req.setStyleSheet('color:#999')
        v1.addWidget(req)

        self.roles = QPlainTextEdit()
        self.roles.setObjectName("roles")
        self.roles.setMinimumHeight(100)
        self.roles.setPlainText(params.get("f5tts_role",''))
        self.roles.setPlaceholderText(
            tr("Reference Audio#Audio Text"))
        v1.addWidget(self.roles)


        self.save = QPushButton()
        self.save.setObjectName("save")
        self.save.setMinimumSize(QSize(0, 35))
        self.save.clicked.connect(self._save)

        v1.addWidget(self.save)
        self.retranslateUi(refform)
        QMetaObject.connectSlotsByName(refform)

    def _save(self):
        role = self.roles.toPlainText().strip()
        if not role:
            return show_error(tr("Please upload reference audio in wav format"))
        
        role_list=role.split("\n")
        for i,it in enumerate(role_list):
            _tmp=it.split('#')
            if len(_tmp)!=2:
                return show_error(tr('ensure that each line is separated into two parts using',{it}))
            
            if Path(f'{ROOT_DIR}/f5-tts/{_tmp[0]}').exists():
                continue
            if Path(f'{ROOT_DIR}/f5-tts/{_tmp[0]}.wav').exists():
                role_list[i]=f'{_tmp[0]}.wav#{_tmp[1]}'
                continue
            return show_error(tr('ensure that the reference audio is in wav format and saved',_tmp[0],f'{ROOT_DIR}/f5-tts'))
        
        role="\n".join(role_list)
        params["f5tts_role"] = role
        params.save()
        set_process(text='', type="refreshtts")
        self.close()

    def retranslateUi(self, refform):
        refform.setWindowTitle(tr("Set reference audio"))
        self.save.setText(tr("Save"))
        
