# run again.  Do not edit this file unless you know what you are doing.
import re
from pathlib import Path
from typing import List

from PySide6 import QtCore, QtWidgets
from PySide6.QtGui import Qt, QIcon
from PySide6.QtWidgets import QFileDialog
from videotrans.configure.config import ROOT_DIR, tr, app_cfg, settings

# ultrafast 、 superfast 、 veryfast 、 faster 、 fast 、 medium （默认）、 slow和veryslow
# 处理速度越来越慢，输出视频压缩率和质量越来越高，视频尺寸也将变小

# 中文注释 界面ui控制
from videotrans.util.help_misc import open_url
from .advset_keys import notices,  ComboBox_List, ComboBox_Data


class Ui_setini(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowIcon(QIcon(f"{ROOT_DIR}/videotrans/styles/icon.ico"))
        self.setupUi(self)


    def get_target(self):
        dirname = QFileDialog.getExistingDirectory(self, tr('selectsavedir'), Path.home().as_posix())
        if dirname:
            dirpath = Path(dirname)
            HOME_DIR = dirpath.as_posix()
            settings['homedir'] = HOME_DIR
            self.homedir_btn.setText(HOME_DIR)
            settings.save()

    def _is_comboBox(self,key):
        return key in ComboBox_List

    def _get_comboBox(self,key) -> List[str]:
        return ComboBox_Data.get(key, [""])

    def _build_setting_row(self, key,title, tips_str, parent_layout):
        """构建单行设置项（标签按钮 + 输入控件）并添加到 parent_layout"""
        tmp = QtWidgets.QHBoxLayout()
        tmp_0 = QtWidgets.QPushButton()
        tmp_0.setStyleSheet("""background-color:transparent;""")

        tmp_0.setText(title)
        tmp_0.setObjectName(f'btn_{key}')
        tmp_0.setToolTip(tips_str)
        tmp.addWidget(tmp_0)

        val = str(settings.get(key, ""))
        # 下拉列表 comboBox
        if self._is_comboBox(key):
            combobox_data = self._get_comboBox(key)
            tmp1 = QtWidgets.QComboBox()
            tmp1.addItems(combobox_data)

            if key=='llm_ai_type':
                tmp1.setCurrentIndex(int(float(val)) if re.match(r'^\d+$',val) else 0 )
            elif val in combobox_data:
                tmp1.setCurrentText(val)
            tmp1.setObjectName(key)
            tmp1.setToolTip(tips_str)
            tmp.addWidget(tmp1)
            tmp.addStretch(1)
            parent_layout.addLayout(tmp)
            return
        # 设置家目录按钮
        if key == 'homedir':
            self.homedir_btn = QtWidgets.QPushButton()
            self.homedir_btn.setCursor(Qt.PointingHandCursor)
            self.homedir_btn.setText(str(val))
            self.homedir_btn.setToolTip(
                tr("Click on Set Home Directory to save the result files for video separation, subtitle translation, subtitle dubbing, etc."))
            self.homedir_btn.clicked.connect(self.get_target)
            self.homedir_btn.setObjectName(key)
            tmp.addWidget(self.homedir_btn)
            tmp.addStretch(1)
            parent_layout.addLayout(tmp)
            return
        # 是checkbox 复选框
        if val.lower() in ['true', 'false']:
            tmp_1 = QtWidgets.QCheckBox()
            tmp_1.setChecked(True if val.lower() == 'true' else False)
            tmp_1.setToolTip(tips_str)
            tmp_1.setObjectName(key)

            tmp.addWidget(tmp_1)
            tmp.addStretch(1)
            parent_layout.addLayout(tmp)
            return

        # 普通文本框 字符串或数字
        tmp_1 = QtWidgets.QLineEdit()
        tmp_1.setMinimumSize(QtCore.QSize(0, 30))
        tmp_1.setText(str(val))
        tmp_1.setPlaceholderText(tips_str)
        tmp_1.setToolTip(tips_str)
        tmp_1.setObjectName(key)
        tmp.addWidget(tmp_1)

        parent_layout.addLayout(tmp)

    def setupUi(self, setini):
        self.centralwidget = QtWidgets.QWidget(setini)
        self.centralwidget.setObjectName("centralwidget")
        self.has_done = False
        setini.setObjectName("setini")
        setini.setMinimumSize(900, 670)
        self.setWindowFlags(Qt.WindowStaysOnTopHint)
        self.layout = QtWidgets.QVBoxLayout(setini)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.setObjectName("layout")

        action_layout = QtWidgets.QHBoxLayout()
        # 顶部提示文字
        label_title = QtWidgets.QLabel()
        label_title.setText(
            tr("Clicking  title on the left will show help"))
        label_title.setObjectName("label_head")
        label_title.setAlignment(Qt.AlignCenter)
        label_title.setStyleSheet("""color:#eeeeee;text-align:center;font-size:16px;margin-top:10px""")
        self.layout.addWidget(label_title)

        self.homedir_btn = None

        # 使用 QTabWidget 替代原来的双列滚动布局，每个模块一个标签卡
        self.tab_widget = QtWidgets.QTabWidget()
        self.tab_widget.setObjectName("tab_widget")
        self.tab_widget.setStyleSheet("""
            QTabWidget::pane {
                border: 1px solid #3a3a3a;
                background-color: #2b2b2b;
            }
            QTabBar::tab {
                background-color: #3a3a3a;
                color: #cccccc;
                padding: 8px 18px;
                margin-right: 2px;
                border-top-left-radius: 4px;
                border-top-right-radius: 4px;
                font-size: 13px;
            }
            QTabBar::tab:selected {
                background-color: #148CD2;
                color: #ffffff;
                font-weight: bold;
            }
            QTabBar::tab:hover:!selected {
                background-color: #4a4a4a;
            }
        """)

        for headkey, item in notices.items():
            # 每个标签页内部使用滚动区域，防止内容溢出
            tab_scroll = QtWidgets.QScrollArea()
            tab_scroll.setWidgetResizable(True)
            tab_scroll.setAlignment(Qt.AlignmentFlag.AlignTop)
            tab_scroll.setStyleSheet("QScrollArea{border:none;background-color:transparent;}")

            tab_content = QtWidgets.QWidget()
            tab_layout = QtWidgets.QVBoxLayout(tab_content)
            tab_layout.setContentsMargins(10, 10, 10, 10)

            for key in item:
                if key.startswith('initial_prompt_'):
                    _text=tr("Initial prompt for the Whisper model for speech",tr(key.split('_')[2]))
                    self._build_setting_row(key, _text,_text,  tab_layout)
                else:
                    self._build_setting_row(key, tr(f'{key}_title'), tr(f'{key}_notice'),  tab_layout)

            tab_layout.addStretch()
            tab_scroll.setWidget(tab_content)
            self.tab_widget.addTab(tab_scroll, tr(f"{headkey}_head"))

        # stretch=1 让 tab_widget 填充剩余空间，按钮固定在底部不会遮挡内容
        self.layout.addWidget(self.tab_widget, stretch=1)

        self.set_ok = QtWidgets.QPushButton()
        self.set_ok.setMinimumSize(QtCore.QSize(160, 40))
        self.set_ok.setObjectName("set_ok")
        self.set_ok.setCursor(Qt.PointingHandCursor)
        self.set_ok.setStyleSheet("""
            QPushButton {
                color: #ffffff;
                background-color: #148CD2;
                font-size: 15px;
                font-weight: bold;
                border-radius: 5px;
                padding: 6px 24px;
            }
            QPushButton:hover {
                background-color: #0e6fa0;
            }
            QPushButton:pressed {
                background-color: #0b5a82;
            }
        """)

        self.help_btn = QtWidgets.QPushButton()
        self.help_btn.setObjectName("help_btn")
        self.help_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.help_btn.setCursor(Qt.PointingHandCursor)
        self.help_btn.setStyleSheet("""
            QPushButton {
                color: #aaaaaa;
                background-color: transparent;
                font-size: 12px;
                border: 1px solid #555555;
                border-radius: 4px;
                padding: 4px 12px;
            }
            QPushButton:hover {
                color: #ffffff;
                border-color: #148CD2;
            }
        """)
        self.help_btn.setText(tr("Fill out the tutorial"))
        self.help_btn.clicked.connect(lambda: open_url(url='https://pyvideotrans.com/adv'))

        action_layout.addStretch()
        action_layout.addWidget(self.set_ok)
        action_layout.addWidget(self.help_btn)
        action_layout.addStretch()

        self.layout.addLayout(action_layout)

        self.retranslateUi(setini)
        QtCore.QMetaObject.connectSlotsByName(setini)

    def update_ui(self):
        obj = self.findChild(QtWidgets.QComboBox, 'lang')
        current_text = obj.currentText()
        _support = {}
        for it in Path(f'{ROOT_DIR}/videotrans/language').glob('*.json'):
            if it.stat().st_size > 0:
                _support[it.stem] = it.as_posix()
        # 有变化时
        if _support and _support.keys() != app_cfg.SUPPORT_LANG.keys():
            app_cfg.SUPPORT_LANG = _support
            obj.clear()
            obj.addItems(list(_support.keys()))
            if current_text in _support:
                obj.setCurrentText(current_text)

    def retranslateUi(self, setini):
        setini.setWindowTitle(tr("Options"))
        self.set_ok.setText(tr("Save and Close"))
