# run again.  Do not edit this file unless you know what you are doing.

from PySide6 import QtCore, QtWidgets
from PySide6.QtCore import (QMetaObject, Qt)
from PySide6.QtGui import (QCursor)
from PySide6.QtWidgets import (QHBoxLayout, QLabel)
from videotrans.configure.config import tr


class Ui_videoandsrt(object):
    def setupUi(self, videoandsrt):
        self.has_done = False
        if not videoandsrt.objectName():
            videoandsrt.setObjectName(u"videoandsrt")
        videoandsrt.setMinimumSize(700, 400)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(videoandsrt.sizePolicy().hasHeightForWidth())
        videoandsrt.setSizePolicy(sizePolicy)

        self.horizontalLayout_3 = QHBoxLayout(videoandsrt)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")

        # start
        self.v3 = QtWidgets.QVBoxLayout()
        self.v3.setObjectName("v3")

        # h3
        self.h3 = QtWidgets.QHBoxLayout()
        self.h3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel()
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 40))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.h3.addWidget(self.label_4, 0, QtCore.Qt.AlignTop)

        self.folder = QtWidgets.QLineEdit()
        self.folder.setMinimumSize(QtCore.QSize(0, 40))
        self.folder.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.folder.setReadOnly(True)
        self.folder.setObjectName("folder")
        self.h3.addWidget(self.folder, 0, QtCore.Qt.AlignTop)

        self.folder_btn = QtWidgets.QPushButton()
        self.folder_btn.setMinimumSize(QtCore.QSize(150, 40))
        self.folder_btn.setObjectName("folder_btn")
        self.h3.addWidget(self.folder_btn, 0, QtCore.Qt.AlignTop)

        # v3 add h3
        self.v3.addLayout(self.h3)

        self.labeltips = QLabel()
        self.labeltips.setStyleSheet('''color:#999''')
        self.v3.addWidget(self.labeltips)

        # h6
        self.h7 = QtWidgets.QHBoxLayout()
        self.h7.setObjectName("h7")

        
        self.set_ass=QtWidgets.QPushButton()
        self.set_ass.setCursor(Qt.PointingHandCursor)
        self.set_ass.setText(tr('Modify hard subtitle style'))
        
        self.maxlenlabel = QtWidgets.QLabel()
        self.maxlenlabel.setText(tr("Hard Subtitle Line Characters"))
        self.maxlen = QtWidgets.QLineEdit()
        self.maxlen.setText('30')

        self.layout_form0 = QtWidgets.QFormLayout()
        self.layout_form0.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.maxlenlabel)
        self.layout_form0.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.maxlen)

        self.issoft = QtWidgets.QCheckBox()
        self.issoft.setObjectName("issoft")
        self.issoft.setChecked(False)
        self.issoft.setText(tr("Embedded Soft Subtitles"))

        self.layout_form = QtWidgets.QFormLayout()

        self.languagelabel = QtWidgets.QLabel()
        self.languagelabel.setText(tr("soft subtitle language"))
        self.languagelabel.setStyleSheet('color:#777')
        self.language = QtWidgets.QComboBox()
        self.language.setMinimumSize(QtCore.QSize(0, 30))
        self.language.setObjectName("language")
        self.language.setDisabled(True)
        self.issoft.toggled.connect(self.update_language)

        self.layout_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.languagelabel)
        self.layout_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.language)

        self.h7.addWidget(self.set_ass)
        self.h7.addLayout(self.layout_form0)
        self.h7.addStretch()
        self.h7.addWidget(self.issoft)
        self.h7.addLayout(self.layout_form)

        self.v3.addLayout(self.h7)

        self.startbtn = QtWidgets.QPushButton()
        self.startbtn.setMinimumSize(QtCore.QSize(250, 40))
        self.startbtn.setObjectName("startbtn")
        self.startbtn.setCursor(QCursor(Qt.PointingHandCursor))
        self.v3.addWidget(self.startbtn)

        self.loglabel = QLabel()
        self.loglabel.setStyleSheet('''color:#148cd2''')
        self.v3.addWidget(self.loglabel)
        self.v3.addStretch()

        self.h8 = QtWidgets.QHBoxLayout()
        self.h8.setObjectName("horizontalLayout_20")
        self.opendir = QtWidgets.QPushButton()
        self.opendir.setMinimumSize(QtCore.QSize(0, 30))
        self.opendir.setStyleSheet("""background-color:transparent""")
        self.opendir.setObjectName("opendir")
        self.opendir.setCursor(QCursor(Qt.PointingHandCursor))
        self.h8.addWidget(self.opendir)
        self.v3.addLayout(self.h8)

        # end
        self.horizontalLayout_3.addLayout(self.v3)

        videoandsrt.setWindowTitle(tr("video/subtitles merger"))
        self.retranslateUi()

        QMetaObject.connectSlotsByName(videoandsrt)

    def update_language(self, state):
        self.languagelabel.setStyleSheet(f"""color:#f1f1f1""" if state else 'color:#777777')
        self.language.setDisabled(False if state else True)

    def retranslateUi(self):

        self.labeltips.setText(
            tr("Will merge video and srt subtitles with the same name in that folder, e.g. 1.mp4 and 1.srt"))

        self.label_4.setText(tr("Video and subtitle folders"))
        self.folder_btn.setText(tr("Select folder"))
        self.folder.setPlaceholderText(
            tr("Select the folder where the video and subtitles of the same name are located"))
        self.startbtn.setText(tr("Start operating"))
        self.opendir.setText(tr("Open the results catalog"))
