# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets
from PySide6.QtCore import Qt
from videotrans.configure.config import tr
from videotrans.util import tools


class Ui_whisperx(object):
    def setupUi(self, whisperxform):
        self.has_done = False
        whisperxform.setObjectName("whisperxform")
        whisperxform.setWindowModality(QtCore.Qt.NonModal)
        whisperxform.resize(800, 400)

        self.verticalLayout = QtWidgets.QVBoxLayout(whisperxform)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        self.helplabel=QtWidgets.QLabel(tr('whisperx-tips'))
        self.helplabel.setWordWrap(True)
        self.verticalLayout.addWidget(self.helplabel)

        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")

        self.label = QtWidgets.QLabel()
        self.label.setMinimumSize(QtCore.QSize(100, 35))
        self.label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")

        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.api_url = QtWidgets.QLineEdit()
        self.api_url.setMinimumSize(QtCore.QSize(0, 35))
        self.api_url.setObjectName("api_url")

        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.api_url)
        self.verticalLayout.addLayout(self.formLayout_2)



        self.set = QtWidgets.QPushButton()
        self.set.setMinimumSize(QtCore.QSize(0, 35))
        self.set.setObjectName("set")

        self.test = QtWidgets.QPushButton()
        self.test.setMinimumSize(QtCore.QSize(0, 30))
        self.test.setObjectName("test")

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: tools.open_url(url='https://pyvideotrans.com/whisperx-api'))

        self.layout_btn = QtWidgets.QHBoxLayout()
        self.layout_btn.setObjectName("layout_btn")

        self.layout_btn.addWidget(self.set)
        self.layout_btn.addWidget(self.test)
        self.layout_btn.addWidget(help_btn)

        self.verticalLayout.addLayout(self.layout_btn)

        self.retranslateUi(whisperxform)
        QtCore.QMetaObject.connectSlotsByName(whisperxform)

    def retranslateUi(self, whisperxform):
        whisperxform.setWindowTitle('WhipserX-API')

        self.label.setText(tr('API URL'))
        self.api_url.setPlaceholderText(tr('API URL'))
        self.set.setText(tr("Save"))
        self.test.setText(tr("Test"))
