# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets
from PySide6.QtCore import Qt

from videotrans.configure.config import tr,app_cfg,params,settings,logger
from videotrans.util import tools


class Ui_xaittsform(object):
    def setupUi(self, xaittsform):
        self.has_done = False
        xaittsform.setObjectName("xaittsform")
        xaittsform.setWindowModality(QtCore.Qt.NonModal)
        xaittsform.resize(600, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(xaittsform.sizePolicy().hasHeightForWidth())
        xaittsform.setSizePolicy(sizePolicy)
        xaittsform.setMaximumSize(QtCore.QSize(600, 300))

        v1 = QtWidgets.QVBoxLayout(xaittsform)



        h2 = QtWidgets.QHBoxLayout()
        self.label_2 = QtWidgets.QLabel(xaittsform)
        self.label_2.setMinimumSize(QtCore.QSize(0, 35))
        self.label_2.setSizeIncrement(QtCore.QSize(0, 35))
        self.label_2.setObjectName("label_2")
        self.xaitts_key = QtWidgets.QLineEdit(xaittsform)
        self.xaitts_key.setMinimumSize(QtCore.QSize(0, 35))
        self.xaitts_key.setObjectName("xaitts_key")
        h2.addWidget(self.label_2)
        h2.addWidget(self.xaitts_key)
        v1.addLayout(h2)


        h4 = QtWidgets.QHBoxLayout()

        self.set_xaitts = QtWidgets.QPushButton(xaittsform)
        self.set_xaitts.setMinimumSize(QtCore.QSize(0, 35))
        self.set_xaitts.setObjectName("set_xaitts")

        self.test_xaitts = QtWidgets.QPushButton(xaittsform)
        self.test_xaitts.setMinimumSize(QtCore.QSize(0, 30))
        self.test_xaitts.setObjectName("test_xaitts")

        help_btn = QtWidgets.QPushButton()
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: tools.open_url(url='https://pyvideotrans.com/xaitts'))

        h4.addWidget(self.set_xaitts)
        h4.addWidget(self.test_xaitts)
        h4.addWidget(help_btn)
        v1.addLayout(h4)

        self.retranslateUi(xaittsform)
        QtCore.QMetaObject.connectSlotsByName(xaittsform)

    def update_ui(self):

        if params.get("xaitts_key",''):
            self.xaitts_key.setText(params.get("xaitts_key",''))

    def retranslateUi(self, xaittsform):
        xaittsform.setWindowTitle("XAI TTS")
        self.set_xaitts.setText(tr("Save"))
        self.test_xaitts.setText(tr("Test"))
        self.xaitts_key.setPlaceholderText("SK")
        self.label_2.setText(tr("SK"))
