# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ott.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtWidgets import QLabel

from videotrans.configure import config


class Ui_zhrecognform(object):
    def setupUi(self, zhrecogn):
        zhrecogn.setObjectName("zhrecogn")
        zhrecogn.setWindowModality(QtCore.Qt.NonModal)
        zhrecogn.resize(500, 223)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(zhrecogn.sizePolicy().hasHeightForWidth())
        zhrecogn.setSizePolicy(sizePolicy)
        zhrecogn.setMaximumSize(QtCore.QSize(500, 300))
        self.gridLayout = QtWidgets.QGridLayout(zhrecogn)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(zhrecogn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 35))
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")

        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.zhrecogn_address = QtWidgets.QLineEdit(zhrecogn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zhrecogn_address.sizePolicy().hasHeightForWidth())
        self.zhrecogn_address.setSizePolicy(sizePolicy)
        self.zhrecogn_address.setMinimumSize(QtCore.QSize(210, 35))
        self.zhrecogn_address.setObjectName("zhrecogn_address")
        
        
        
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.zhrecogn_address)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        

        self.set = QtWidgets.QPushButton(zhrecogn)
        self.set.setMinimumSize(QtCore.QSize(0, 35))
        self.set.setObjectName("set")

        self.test = QtWidgets.QPushButton(zhrecogn)
        self.test.setMinimumSize(QtCore.QSize(0, 30))
        self.test.setObjectName("test")

        label=QLabel("该项目地址 https://github.com/jianchang512/zh_recogn")
        self.verticalLayout_2.addWidget(label)

        self.layout_btn = QtWidgets.QHBoxLayout()
        self.layout_btn.setObjectName("layout_btn")

        self.layout_btn.addWidget(self.set)
        self.layout_btn.addWidget(self.test)

        self.verticalLayout_2.addLayout(self.layout_btn)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(zhrecogn)
        QtCore.QMetaObject.connectSlotsByName(zhrecogn)

    def retranslateUi(self, zhrecogn):
        zhrecogn.setWindowTitle("zh_recogn中文语音识别")
        self.label.setText("http接口地址")
        self.zhrecogn_address.setPlaceholderText('填写zh_recogn项目启动后的http接口地址')
        self.set.setText('保存')
        self.test.setText('测试')
