# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets
from PySide6.QtCore import Qt
from videotrans.configure.config import tr
from videotrans.util import tools


class Ui_zijierecognform(object):
    def setupUi(self, zijierecognform):
        self.has_done = False
        zijierecognform.setObjectName("zijierecognform")
        zijierecognform.setWindowModality(QtCore.Qt.NonModal)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(zijierecognform.sizePolicy().hasHeightForWidth())
        zijierecognform.setSizePolicy(sizePolicy)
        zijierecognform.setMaximumSize(QtCore.QSize(800, 300))

        self.verticalLayout = QtWidgets.QVBoxLayout(zijierecognform)
        self.verticalLayout.setObjectName("verticalLayout")

        labetips=QtWidgets.QLabel(
            "字节火山有太多名称类似的语音识别产品，只有【语音识别大模型】下【大模型录音文件极速版识别API】才可在此使用"
            "\n其他字节大模型语音识别产品，或无法直接上传本地文件，或有其他限制，目前极速版最适合。"
            "\n这和【字节火山字幕生成】也非同个产品，本API支持语言更多效果更好，并且支持说话人识别"
            "\n使用前请务必 "+tr("Fill out the tutorial"))
        self.verticalLayout.addWidget(labetips)

        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(zijierecognform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 35))
        self.label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.zijierecognmodel_appid = QtWidgets.QLineEdit(zijierecognform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zijierecognmodel_appid.sizePolicy().hasHeightForWidth())
        self.zijierecognmodel_appid.setSizePolicy(sizePolicy)
        self.zijierecognmodel_appid.setMinimumSize(QtCore.QSize(210, 35))
        self.zijierecognmodel_appid.setObjectName("zijierecognmodel_appid")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.zijierecognmodel_appid)
        self.verticalLayout.addLayout(self.formLayout_2)

        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(zijierecognform)
        self.label_2.setMinimumSize(QtCore.QSize(100, 35))
        self.label_2.setSizeIncrement(QtCore.QSize(0, 35))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)

        self.zijierecognmodel_token = QtWidgets.QLineEdit(zijierecognform)
        self.zijierecognmodel_token.setMinimumSize(QtCore.QSize(210, 35))
        self.zijierecognmodel_token.setObjectName("zijierecognmodel_token")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.zijierecognmodel_token)
        self.verticalLayout.addLayout(self.formLayout)


        h4 = QtWidgets.QHBoxLayout()

        self.set = QtWidgets.QPushButton(zijierecognform)
        self.set.setMinimumSize(QtCore.QSize(0, 35))
        self.set.setObjectName("set")

        self.test = QtWidgets.QPushButton(zijierecognform)
        self.test.setMinimumSize(QtCore.QSize(0, 35))
        self.test.setObjectName("test")

        help_btn = QtWidgets.QPushButton(zijierecognform)
        help_btn.setMinimumSize(QtCore.QSize(0, 35))
        help_btn.setStyleSheet("background-color: rgba(255, 255, 255,0)")
        help_btn.setObjectName("help_btn")
        help_btn.setCursor(Qt.PointingHandCursor)
        help_btn.setText(tr("Fill out the tutorial"))
        help_btn.clicked.connect(lambda: tools.open_url(url='https://pyvideotrans.com/zijierecognmodel'))

        h4.addWidget(self.set)
        h4.addWidget(self.test)
        h4.addWidget(help_btn)
        self.verticalLayout.addLayout(h4)

        self.retranslateUi(zijierecognform)
        QtCore.QMetaObject.connectSlotsByName(zijierecognform)
    def update_ui(self):
        from videotrans.configure import config
        self.zijierecognmodel_appid.setText(config.params.get("zijierecognmodel_appid",''))
        self.zijierecognmodel_token.setText(config.params.get("zijierecognmodel_token",''))

    def retranslateUi(self, zijierecognform):
        zijierecognform.setWindowTitle(tr('VolcEngine STT'))
        self.label.setText("AppID")
        self.label_2.setText("Access Token")
        self.set.setText(tr("Save"))
        self.test.setText(tr("Test"))
