# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtWidgets

from videotrans.configure import config
from videotrans.configure.config import tr
from videotrans.util import tools


class Ui_zijiehuoshanform(object):
    def setupUi(self, zijiehuoshanform):
        self.has_done = False
        zijiehuoshanform.setObjectName("zijiehuoshanform")
        zijiehuoshanform.setWindowModality(QtCore.Qt.NonModal)
        zijiehuoshanform.resize(600, 570)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(zijiehuoshanform.sizePolicy().hasHeightForWidth())
        zijiehuoshanform.setSizePolicy(sizePolicy)
        zijiehuoshanform.setMaximumSize(QtCore.QSize(600, 570))

        v1 = QtWidgets.QVBoxLayout(zijiehuoshanform)
        h1 = QtWidgets.QHBoxLayout()
        h2 = QtWidgets.QHBoxLayout()
        h3 = QtWidgets.QHBoxLayout()

        self.label_2 = QtWidgets.QLabel(zijiehuoshanform)
        self.label_2.setMinimumSize(QtCore.QSize(0, 35))
        self.label_2.setSizeIncrement(QtCore.QSize(0, 35))
        self.label_2.setObjectName("label_2")
        self.zijiehuoshan_key = QtWidgets.QLineEdit(zijiehuoshanform)
        self.zijiehuoshan_key.setMinimumSize(QtCore.QSize(0, 35))
        self.zijiehuoshan_key.setObjectName("zijiehuoshan_key")
        h1.addWidget(self.label_2)
        h1.addWidget(self.zijiehuoshan_key)
        v1.addLayout(h1)

        self.label_3 = QtWidgets.QLabel(zijiehuoshanform)
        self.label_3.setObjectName("label_3")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.zijiehuoshan_model = QtWidgets.QComboBox(zijiehuoshanform)
        self.zijiehuoshan_model.setMinimumSize(QtCore.QSize(0, 35))
        self.zijiehuoshan_model.setObjectName("zijiehuoshan_model")
        self.zijiehuoshan_model.setSizePolicy(sizePolicy)
        h2.addWidget(self.label_3)
        h2.addWidget(self.zijiehuoshan_model)
        v1.addLayout(h2)

        self.label_allmodels = QtWidgets.QLabel(zijiehuoshanform)
        self.label_allmodels.setObjectName("label_allmodels")
        self.label_allmodels.setText(tr('Fill in all inference access points, and you can select them above'))
        v1.addWidget(self.label_allmodels)

        self.edit_allmodels = QtWidgets.QPlainTextEdit(zijiehuoshanform)
        self.edit_allmodels.setObjectName("edit_allmodels")
        v1.addWidget(self.edit_allmodels)

        self.label_4 = QtWidgets.QLabel(zijiehuoshanform)
        # self.label_4.setGeometry(QtCore.QRect(10, 285, 571, 21))
        self.label_4.setObjectName("label_4")
        v1.addWidget(self.label_4)

        self.zijiehuoshan_template = QtWidgets.QPlainTextEdit(zijiehuoshanform)
        # self.zijiehuoshan_template.setGeometry(QtCore.QRect(10, 310, 571, 151))
        self.zijiehuoshan_template.setObjectName("zijiehuoshan_template")
        self.zijiehuoshan_template.setReadOnly(True)
        v1.addWidget(self.zijiehuoshan_template)

        self.set_zijiehuoshan = QtWidgets.QPushButton(zijiehuoshanform)
        self.set_zijiehuoshan.setMinimumSize(QtCore.QSize(0, 35))
        self.set_zijiehuoshan.setObjectName("set_zijiehuoshan")

        self.test_zijiehuoshan = QtWidgets.QPushButton(zijiehuoshanform)
        self.test_zijiehuoshan.setMinimumSize(QtCore.QSize(0, 30))
        self.test_zijiehuoshan.setObjectName("test_zijiehuoshan")

        self.label_0 = QtWidgets.QPushButton(zijiehuoshanform)
        self.label_0.setText(tr('Click to open help page'))
        self.label_0.setStyleSheet("background-color: rgba(255, 255, 255,0);text-align:left")
        self.label_0.clicked.connect(lambda: tools.open_url('https://pyvideotrans.com/zijiehuoshan'))
        self.label_0.setCursor(QtCore.Qt.PointingHandCursor)
        h3.addWidget(self.set_zijiehuoshan)
        h3.addWidget(self.test_zijiehuoshan)
        h3.addWidget(self.label_0)
        v1.addLayout(h3)

        self.zijiehuoshan_template.setPlainText((tr("Prompt: Please open the {} file directly to modify it", 'zijie' if config.defaulelang=='zh' else 'zijie-en')))
        self.retranslateUi(zijiehuoshanform)
        QtCore.QMetaObject.connectSlotsByName(zijiehuoshanform)

    def update_ui(self):
        from videotrans.configure import config
        config.settings = config.parse_init()
        allmodels_str = config.settings.get('zijiehuoshan_model','')
        allmodels = config.settings.get('zijiehuoshan_model','').split(',')
        self.zijiehuoshan_model.clear()
        self.zijiehuoshan_model.addItems(allmodels)
        self.edit_allmodels.setPlainText(allmodels_str)

        self.zijiehuoshan_key.setText(config.params.get("zijiehuoshan_key",''))
        if config.params.get("zijiehuoshan_model",'') in allmodels:
            self.zijiehuoshan_model.setCurrentText(config.params.get("zijiehuoshan_model",''))
    def retranslateUi(self, zijiehuoshanform):
        zijiehuoshanform.setWindowTitle(tr("ByteDance Ark"))
        self.label_3.setText(tr('Selecting an Inference Access Point'))
        self.label_4.setText(tr("{lang} represents the target language name, do not delete it."))
        self.set_zijiehuoshan.setText(tr('Save'))
        self.test_zijiehuoshan.setText(tr('Test'))
        self.label_2.setText(tr("SK"))
